### ISSUE TITLE
Hello - Angular CLI Beta 15 (Webpack 2) Troubles

### ISSUE THREAD

**Issue by jwuliger** [mseemann/angular2-mdl#100]
Hello,

Awesome wrapper for MDL! I am trying to use angular2-mdl with a freshly made a few hours ago app using the Angular CLI v1.0.0-beta.15.

I was able to easily get the SASS to load in my bundle without a hitch, however I am having trouble trying to import `MdlModule` into my root AppModule. I am getting 2 errors. I was hoping for some help to figure out what I am doing wrong. I am assuming an issue revolving around SystemJS vs Webpack.

*Error 1*
`Uncaught Error: Unexpected value 'undefined' imported by the module 'AppModule'`

*Error 2*
`Uncaught Error: Unexpected value 'undefined' imported by the module 'AppModule'`

Please see attached the screen grab of my chrome dev console.
![error](https://cloud.githubusercontent.com/assets/14036569/18718984/66991ddc-7ff3-11e6-97e7-af5d18e08247.PNG)

The Webpack CLI seems to really abstract the configuration from a normal Webpack app.

Here is my `angular-cli.json` file:

```
{
	"project": {
		"version": "1.0.0-beta.15",
		"name": "admin-site"
	},
	"apps": [
		{
			"root": "src",
			"outDir": "dist",
			"assets": "assets",
			"index": "index.html",
			"main": "main.ts",
			"test": "test.ts",
			"tsconfig": "tsconfig.json",
			"prefix": "app",
			"mobile": false,
			"styles": [
				"styles.scss",
				"../node_modules/angular2-mdl/src/scss-mdl/material-design-lite.scss"
			],
			"scripts": [
				"../node_modules/angular2-mdl/dist/components/index.js"
			],
			"environments": {
				"source": "environments/environment.ts",
				"dev": "environments/environment.ts",
				"prod": "environments/environment.prod.ts"
			}
		}
	],
	"addons": [],
	"packages": [],
	"e2e": {
		"protractor": {
			"config": "./protractor.conf.js"
		}
	},
	"test": {
		"karma": {
			"config": "./karma.conf.js"
		}
	},
	"defaults": {
		"styleExt": "scss",
		"prefixInterfaces": false
	}
}
```

Last but not least my `app.module.ts`:

```
import { BrowserModule } from '@angular/platform-browser';
import { CUSTOM_ELEMENTS_SCHEMA, NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { MdlModule } from 'angular2-mdl';
import { CoreModule } from './core/core.module';

import './core/rxjs-extensions';
import { AppComponent } from './app.component';
import { AppRoutingModule } from './app.routing';
import { LandingComponent } from './landing/landing.component';

@NgModule( {
	declarations: [
		AppComponent,
		LandingComponent
	],
	imports: [
		BrowserModule,
		FormsModule,
		HttpModule,
		MdlModule,
		CoreModule
	],
	providers: [],
	schemas: [ CUSTOM_ELEMENTS_SCHEMA ],
	bootstrap: [ AppComponent ]
})
export class AppModule { }

```

Thanks in advance for any help!

**Comment by mseemann** [comment]
hi.

why did you add this?
"scripts": [
                "../node_modules/angular2-mdl/dist/components/index.js"
            ],

 You should add angular2-mdl the same way as you add @angular. I guess there is a vendor.ts file anywhere...

**Comment by jwuliger** [comment]
Hello,

Very good point. I had Bootstrap 4 on the brain. I removed the script call from my CLI config and all is well. I do not know why I thought I had to do that with your package.

Thanks very, very much for the help!

**Comment by mseemann** [comment]
no prob:)
