### ISSUE TITLE
The tooltip is getting overshadowed when it is added to an element in the header.

### ISSUE THREAD

**Issue by tiagopsilva** [mseemann/angular2-mdl#1004]
The tooltip is getting overshadowed when it is added to an element in the header.

![image](https://user-images.githubusercontent.com/14366064/26935295-f2c4eb40-4c41-11e7-9761-34b13a077f59.png)

Apparently because of the "will change" css style.

![image](https://user-images.githubusercontent.com/14366064/26935393-372558f6-4c42-11e7-88a4-869ae4b57cc7.png)

Github repository with sample: https://github.com/tiagopsilva/angular2-mdl-tooltip-in-header-issue.git

**Comment by mseemann** [comment]
did you read this: https://github.com/google/material-design-lite/issues/4574 ?

**Comment by tiagopsilva** [comment]
Solved! Thanks
