### ISSUE TITLE
Installation instructions are missing rename of style.css to .scss (Angular CLI project)

### ISSUE THREAD

**Issue by piotrowski** [mseemann/angular2-mdl#1005]
Just tried to install this on a newly created Angular CLI project. The instructions are missing the information, that you have to rename `style.css` to `style.scss`. Got this from looking at https://github.com/mseemann/angular-mdl-a4-angular-cli/commit/5a39894ca607507b67b9df1fcbff95db14597c2c fortunately, so only lost half an hour or so trying to google around.

**Comment by janpio** [comment]
Why did you close this without any comment or remark? 
Isn't this useful information for the usage of the project?
