### ISSUE TITLE
Rollup fails due to a self import error.

### ISSUE THREAD

**Issue by haburka** [mseemann/angular2-mdl#1026]
Mdl-dialog-outlet component apparently imports itself. Rollup version is 0.41.6

`Error: A module cannot import itself
    at error (/var/jenkins_home/workspace/Stage-Deploy/web/build/node_modules/rollup/src/utils/error.js:2:14)
    at Module.error$1 [as error] (/var/jenkins_home/workspace/Stage-Deploy/web/build/node_modules/rollup/src/Module.js:303:2)
    at /var/jenkins_home/workspace/Stage-Deploy/web/build/node_modules/rollup/src/Bundle.js:399:15
  code: 'CANNOT_IMPORT_SELF',
  pos: 37,
  loc: 
   { file: '/var/jenkins_home/workspace/Stage-Deploy/web/build/dist/tmp/node_modules/@angular-mdl/core/components/dialog-outlet/mdl-dialog-outlet.component.ngfactory.js',
     line: 2,
     column: 0 },
  frame: '1: import * as i0 from \'@angular/core\';\n2: import * as i1 from \'./mdl-dialog-outlet.component.ngfactory\';\n   ^\n3: import * as i2 from \'@angular-mdl/core/components/dialog-outlet/mdl-dialog-outlet.component\';\n4: import * as i3 from \'@angular-mdl/core/components/dialog-outlet/mdl-dialog-outlet.service\';' `

I am going to find out why this is happening and fix it. It could be unrelated to mdl entirely, I just wanted to make it so that if this is a common issue, it would be documented online.

**Comment by haburka** [comment]
And it's an Angular Issue: [Issue #17389](https://github.com/angular/angular/issues/17389)

**Comment by mseemann** [comment]
👍
