### ISSUE TITLE
Including an mdl-dialog causes things to happen twice

### ISSUE THREAD

**Issue by ulic75** [mseemann/angular2-mdl#1038]
I'm not sure which things, maybe bootstrapping twice?  I see "Angular is running in the development mode. Call enableProdMode() to enable the production mode." twice when I load the application.  If simply remove the <mdl-alert> this no longer happens.

Additionally in my "real" app when the initial route loaded contains any kind of mdl-dialag my components are rendered twice, I assume it's releated.

Demo repo can be found at Angular is running in the development mode. Call enableProdMode() to enable the production mode.  All I did was generate a new app, add @angular-mdl/core, a style sheet, and the demo mdl-alert.

**Comment by alexisvapillon** [comment]
I have the same problem of initial route components loaded twice, in this cases :
 - if the component contains a mdl-dialog
OR
 - if the component uses MdlSnackbarService

The issue seems to be new with Angular 4.2.x : 
 - I don't see this problem with Angular 4.1.3
 - Only with 4.2.x (4.2.5 right now)

**Comment by mseemann** [comment]
I can't reproduce this issue. Maybe someone with this issue can create a plunkr or at least a sample github project to demonstrate the issue. thx.

**Comment by ulic75** [comment]
Whoops, I create a repo, I even started to include some language about it at the end of the issue, but didn't finish my thought.  Sorry about that, https://github.com/ulic75/mdl-dialog-demo

**Comment by ulic75** [comment]
I just saw this on the[ Angular blog](https://blog.angularjs.org/) for 4.2.  I'm not sure if it's related, but I did notice that it was something that was used as part of this component.

> Angular Forms now includes validators for min and max attributes
> You can now bootstrap a component directly by passing an element reference to the bootstrap method of an ApplicationRef

**Comment by mseemann** [comment]
@ulic75 thx! checked your repo. still can't see any issues. That you see

> Angular is running in the development mode. Call enableProdMode() to enable the production mode.

 twice is intended. The `<dialog-outlet></dialog-outlet>` element creates a second angular app. This is required because this element can be placed outside the `<app></app>` and i need to grab the ElementRef for the `dialog-outlet` Element.

maybe you can add some code so I can check this too:

> Additionally in my "real" app when the initial route loaded contains any kind of mdl-dialag my components are rendered twice, I assume it's releated.

**Comment by ulic75** [comment]
It took some fiddling, trying to add different aspects from my app to the test app.  I thought maybe lazy loading, but no.  I think the problem comes when adding nested router-outlets.  Have a look at the latest commit to the repo when you get a chance.  When you go to the heroes route you end up seeing the hero component twice.  Simply remove the mdl-alert and it doesn't happen.

**Comment by mseemann** [comment]
ok. I see the issue now. The issue has started with angular 4.2. I am not ready with the investigation - but here is a workaround:

- remove the dialog-outlet element from your index.html
- In your HerosComponent add the following code:

```
  constructor(mdlDialogService: MdlDialogOutletService, vcRef: ViewContainerRef) {
    mdlDialogService.setDefaultViewContainerRef(vcRef);
  }

```

**Comment by alexisvapillon** [comment]
Thank you very much for the workaround!
Works for me.

I'm using nested router-outlets indeed.

**Comment by jos1337** [comment]
Is it possible to provide the Service on a global level in a root module and set the Ref in a root component and use Dialogs in all child components or do I have to set the ContainerRef in every Component I want to use a Dialog? 
thank you
