### ISSUE TITLE
Reactive Forms Disabled not handled

### ISSUE THREAD

**Issue by TheNumber-4** [mseemann/angular2-mdl#104]
Issue: 
Trying to use mdl-textfield with form control disabled using reactive forms in angular 2.

Expected Behavior:
Field should be disabled

Actual behavior:
EXCEPTION: Error in app.component.html:2:60 caused by: this.valueAccessor.setDisabledState is not a function

[Plunkr](http://plnkr.co/edit/WfMuOthG8SLOSW5hONRC?p=preview)

I would guess this is also an issue on other form controls as well, I would recommend adding a disabled field to the reactive forms example.

**Comment by mseemann** [comment]
this function was introduced in RC6 or RC7. until now i had no time to implement this for all controls that implement the ControlValueAccessor interface. if you need this asap please consider providing a pull request.

**Comment by mseemann** [comment]
with angular 2.0.1 setDisabledState is now optional (https://github.com/angular/angular/pull/11731)
