### ISSUE TITLE
Support AOT

### ISSUE THREAD

**Issue by DzmitryShylovich** [mseemann/angular2-mdl#109]
To be able to compile project in aot mode all 3rd party libs need to publish metadata.json file.
Therefore, you need to compile this project with ngc.

 "angularCompilerOptions": {
    "skipTemplateCodegen": true
  }
Add that to tsconfig and ngc will only generate metadata files and not ngfactories.

Examples: [material2](https://github.com/angular/material2/blob/master/src/lib/tsconfig.json#L30).

**Comment by mseemann** [comment]
is there any official documentation about skipTemplateCodegen?

**Comment by mseemann** [comment]
will be coverd in #110
