### ISSUE TITLE
Tabs are not Responsive

### ISSUE THREAD

**Issue by phystem** [mseemann/angular2-mdl#1090]
Right Now If the Tabs are viewed in mobile like

![image](https://user-images.githubusercontent.com/11405204/28334644-6281fa30-6c19-11e7-8d4d-f6892d298795.png)

So the user can't navigate to next tab. It would be better If there is previous, next button like the one below

![image](https://user-images.githubusercontent.com/11405204/28334690-8f5b9eb2-6c19-11e7-967e-29e89963a4bf.png)

Refer https://material.angularjs.org/latest/demo/tabs

**Comment by mseemann** [comment]
I'm not going to add such a feature for many reasons:
- it seems not to be supported by getmdl.io
- imho it's not the best user experience to have scrollable tabs
- ...

If someone want's to add this feature I can review the pr and add it.
