### ISSUE TITLE
optimize deploy structure

### ISSUE THREAD

**Issue by mseemann** [mseemann/angular2-mdl#110]
the project is based on angular-cli. This isn't an optimal solution for a lib project that's deployed as npm module. This needs to be optimized.
- support for umd modules
yet todo:
- [x] gh-pages deployment
- [x] test npm package
- [x] publish script

**Comment by DzmitryShylovich** [comment]
Rollup is the recommended tool for 3rd party libs due to its effective treeshaking.

**Comment by istiti** [comment]
I tried `ng build --prod --aot` 
I get:
`0% compiling Unexpected value 'MdlModule' imported by the module 'AppModule'`
