### ISSUE TITLE
mouseover event on tab (layout)

### ISSUE THREAD

**Issue by istiti** [mseemann/angular2-mdl#114]
Enhancement:
please apologize it's maybe relative and not to be an issue but I don't know :  I can't apply a mouseover to get index of tab when mouseover on  each tab : Because of component structure even if I put (mouseover) event on each my  <mdl-layout-tab-panel> tag..

Can you add new  Event-listener function that will be fired if the tab is hovered....

Actually we have only  (mdl-layout-tab-active-changed). How can I add another one like mdl-layout-tab-hover)

**Comment by mseemann** [comment]
an attribute like mdl-layout-tab-hover must be implemented in the component. to make it consistent i would implement:

mdl-layout-tab-mouseover
mdl-layout-tab-mouseout

and emit the index of the tab that fires the event.

would this solve your problem?

**Comment by istiti** [comment]
Yes! thanks a lot. It's for when ?

**Comment by mseemann** [comment]
this week should be possible

**Comment by istiti** [comment]
awesome! How can I add this last release, does npmjs updated with this feature? because When I edit file directly in you lib with last change, the file are ignores I think... maybe there is minification before... I wonder if npm install angular2-mdl wll works

**Comment by mseemann** [comment]
it is not released to npm right now. this will be tomorro or an friday.

you can use the master run npm i and after that ng build. this will generate the dist folder.

**Comment by istiti** [comment]
@mseemann you is the version you use  error when ng build:
_It seems like you're using a project generated usin an old version of the angular cli.
the latest cli now uses webpack and inculdes a lot fo improvements, include a simpler workflow, a faster build and smaller bundles._

**Comment by mseemann** [comment]
I know 😀. But i didn't found the time to change the build system. angular-cli is a good solution for apps but not for libs...

It's version 10. But this should not affect ng build. because ng build uses the angular-cli from the package.json and not the globally installed one. 

It's best to wait until tomorrow for a npm release.

**Comment by mseemann** [comment]
released in npm version 1.8.1

**Comment by istiti** [comment]
Awesome and ironically: **IT WORKS !**
