### ISSUE TITLE
How do I make a <mdl-layout-header-row> without a drawer?

### ISSUE THREAD

**Issue by shootdaj** [mseemann/angular2-mdl#115]
I would like to create a page with just the header title in the header row without a drawer or drawer icon. When I try to do this, I get something that looks like this:

![image](https://cloud.githubusercontent.com/assets/1164049/18900602/023ca944-84f8-11e6-8bd7-cc0dcd435dc7.png)

There is a distinct gap on the left of the title. I have tried to track it down using CSS but I'm lost. Is there a way to get rid of that spacing without overriding the CSS?

**Comment by mseemann** [comment]
this can be done with the css class mdl-layout--no-drawer-button. add this to the mdl-layout component: `<mdl-layout class="mdl-layout--no-drawer-button">`....

There is no directive for this right now. The css classes of material design lite are documented here: https://getmdl.io/components/index.html#layout-section

**Comment by shootdaj** [comment]
Ah so this project follows the design of Material Design Lite. I'll keep that in mind for future reference. Thanks.
