### ISSUE TITLE
Is there an expansion panel in angular2-mdl?

### ISSUE THREAD

**Issue by shootdaj** [mseemann/angular2-mdl#116]
I'm looking to use an expansion panel as specified in Material Design specs:

https://material.google.com/components/expansion-panels.html#

Is there anything like that in angular2-mdl or is there any way to accomplish this easily?

**Comment by mseemann** [comment]
material design lite has no expansion panel, thats why this package have no one too.

it should not be to difficult to build: a fixed mdl-button with an arrow down icon and a tittle bit angular2 animation. The shadow can be built with mdl-shadow. If you don't know how, you can crate a feature request in angular2-mdl-ext (https://github.com/mseemann/angular2-mdl-ext) project. This project is for components that are not part of material design lite.

**Comment by shootdaj** [comment]
Thanks for the quick reply. Is there any way you could provide an example of how you would get the angular2 animation to actually open up a card? I did see the ext project, I can create a feature request in there. Thanks again.

**Comment by mseemann** [comment]
plase checkout this article about animations: http://blog.thoughtram.io/angular/2016/09/16/angular-2-animation-important-concepts.html

**Comment by shootdaj** [comment]
Thanks, I'll take a look and see if I can implement this myself.
