### ISSUE TITLE
Not able to change theme with custom colors

### ISSUE THREAD

**Issue by Ninja-Coding-Git** [mseemann/angular2-mdl#1178]
I'm not able to change the default colors, via:

https://github.com/mseemann/angular2-mdl#how-to-use-the-scss-files-from-material-design-lite

I'm ussing Angular 4 and i don't understand the steps, is not clear for me.

I did:

1. Created scss file with:
```
// any-name.scss
@import "../../node_modules/@angular-mdl/core/scss/color-definitions";
// just copying existent colors from external scss
$color-primary: $primaryColor;
$color-primary-dark: $primaryDarkColor;
$color-accent: $accentColor;
$color-primary-contrast: $accentDarkColor;
$color-accent-contrast: $accentDarkColor;
@import "../../node_modules/@angular-mdl/core/scss/material-design-lite";
```
Note: the compiler i'm ussing does not need "~@angular-mdl" (sassLoader)

this file does not override colors, i have to use this scss in html index? or what i do with this, because by it self isn´t overriding colors.

Another Note: The scss compiler, successful exports the css file

**Comment by Ninja-Coding-Git** [comment]
i added 
`<link id="mdl-css" rel="stylesheet" type="text/css" href="assets/any-name.css" />`

and nope :(

**Comment by mseemann** [comment]
please use stackoverflow for general questions how to setup and use scss wth angular-cli. thx.

**Comment by Ninja-Coding-Git** [comment]
the problem is here, because docs are not clear.
