### ISSUE TITLE
MDL Table - Showing cutom values

### ISSUE THREAD

**Issue by jirungaray** [mseemann/angular2-mdl#1183]
IS there some way I can display a custom representation of the item's data? (eg apply a pipe or function to make the value human readable).

Is there something I can set on the table model or do I have to invent a wrapping object and implement the changes there?

**Comment by mseemann** [comment]
no there is not. It's just a really simple table. You can provide html formatted values if you need. Have a look at the diff for the commit that is related to this issue - i have added a demo.
