### ISSUE TITLE
Dark / Light?

### ISSUE THREAD

**Issue by rui-cruz** [mseemann/angular2-mdl#1185]
Hi,

Is there a way to toggle between light and dark theme?

Thank you
Rui

**Comment by mseemann** [comment]
hi, this has been discussed several times (for example: https://github.com/google/material-design-lite/issues/328) but have never landet in material design lite. so it's not supported by this project.

**Comment by rui-cruz** [comment]
Hi,

Are you talking about this? https://material-components-web.appspot.com/

**Comment by mseemann** [comment]
yes. Material Components for the web  (https://github.com/material-components/material-components-web) is the successor to Material Design Lite. but this project only supports Material Design Lite.

**Comment by charlesr1971** [comment]
Dark Mode: As a quick fix, we just need to change the background colour to a dark colour and the text to a light colour. The primary, accent and warning would stay the same.

It would be really great if a Dark theme could be introduced properly though. This would bring MDL Lite in line with Material and Angular Material.

**Comment by charlesr1971** [comment]
MDL Lite is extremely popular with Vanilla JS enthusiasts, so a Dark Mode would be a much appreciated addition.

**Comment by charlesr1971** [comment]
I would actually be happy to add a dark mode, if anyone could give me some pointers, as to where, I should start to insert. 

I would be happy to create a Pull Request and get started. 

I have over 15 years CSS/JS experience...

**Comment by Fever905** [comment]
@charlesr1971 Did you end up doing that dark theme?

**Comment by charlesr1971** [comment]
No. It looks very complicated. 

With Angular Material, it is a breeze, but with mdl lite, it is more complex! I may have another look at this, next week...
