### ISSUE TITLE
New Demo.

### ISSUE THREAD

**Issue by AndreaM16** [mseemann/angular2-mdl#1186]
Hi Michael.

I tried looking for your email but I didn't find it. I Also tried to make a new pull request but it gave me access denied back.

I built a dashboard using your library and deployed it on heroku. The dashboard is a copy of  [MDL Dashboard Demo](https://getmdl.io/templates/dashboard/index.html). I think it will be helpful to other developers wanting to realize something similar.

You can find the demo at [https://angular-mdl-dashboard.herokuapp.com/](https://angular-mdl-dashboard.herokuapp.com/#/home) and the repository at [github.com/AndreaM16/angular-mdl-dashboard](https://github.com/AndreaM16/angular-mdl-dashboard).

If you want to add it as a second demo I'll appreciate really much.

**Comment by mseemann** [comment]
Hi! Thx for this demo app. I have added it to the readme!
