### ISSUE TITLE
Possible issue with mdl-table-selectable initial render

### ISSUE THREAD

**Issue by asarro** [mseemann/angular2-mdl#1206]
Hi I have an issue with using mdl-table-selectable. The selectable component seems to be off on the initial render as shown on the gif:
Im using the code from the demo I found on git.

![tableload](https://user-images.githubusercontent.com/5725101/30699157-e110092e-9edb-11e7-8080-c4c5a1880c60.gif)

` "dependencies": {
    "@angular-mdl/core": "^4.0.8",
    "@angular/animations": "^4.3.6",
    "@angular/common": "^4.3.6",
    "@angular/compiler": "^4.3.6",
    "@angular/core": "^4.3.6",
    "@angular/forms": "^4.3.6",
    "@angular/http": "^4.3.6",
    "@angular/platform-browser": "^4.3.6",
    "@angular/platform-browser-dynamic": "^4.3.6",
    "@angular/platform-server": "^4.3.6",
    "@angular/router": "^4.3.6",`

**Comment by mseemann** [comment]
please craete a plnkr that demosntrates your issue. thx.

**Comment by asarro** [comment]
Hi,
You can use this instead:
https://github.com/asarro/Learning.git

It's pretty much just asp-net angular template updated to 4.4.3. And then I just added mdl and the select table component.

**Comment by asarro** [comment]
I don't know if you'll still action this, but I removed the asp-prerender-module so it doesn't pre-render and it doesn't do that behaviour anymore.
