### ISSUE TITLE
MdlDialogComponent.close() not working

### ISSUE THREAD

**Issue by jirungaray** [mseemann/angular2-mdl#1251]
I have defined a dialog and linked it like so:
 ` @ViewChild('processingDialog')processingDialog:MdlDialogComponent;`

`this.processingDialog.show()`  works as expected, shows the dialog but Immediately calling:
`this.processingDialog.close();`
does nothing.

Tried in Chrome and safari.

**Comment by mseemann** [comment]
please provide a plnkr that demonstrates your issue. thx.
