### ISSUE TITLE
Autocomplete on inputs

### ISSUE THREAD

**Issue by paullryan** [mseemann/angular2-mdl#127]
We should be passing the autocomplete attribute through to the input like we do with the placeholder. See https://html.spec.whatwg.org/multipage/forms.html#autofill for information on autocomplete/autofill.

**Comment by mseemann** [comment]
right...

**Comment by paullryan** [comment]
I'll have a PR ready for this in the next few hours. 

_Side Question: If I do this against master only are you pulling between master and 2.0?_

**Comment by mseemann** [comment]
great!
master will be 2.0. if you need it asap please do it against branch angular2-mdl-1.x
