### ISSUE TITLE
Upgrade to angular v5

### ISSUE THREAD

**Issue by jhasenfuss** [mseemann/angular2-mdl#1289]
It would be nice if this great library would support the new angular v5 :)

Is this planned in the next days/ weeks?

**Comment by mseemann** [comment]
it is already possible to use this lib with angular 5. You just need to ignore the warnings during npm install or yarn. The package.json will be updated in the next days.

**Comment by jhasenfuss** [comment]
Hi, thanks for your reply.
Today i've updated all versions to their latest and everything works as you said 👍 😄
