### ISSUE TITLE
confirm dialog ESC keytouch return true not false

### ISSUE THREAD

**Issue by istiti** [mseemann/angular2-mdl#133]
## BUG ?
Confirm dialog when we click NO `choosedOption==0`, 
when we click YES `choosedOption==1`

when ESC (key touche) `choosedOption==1` instead 0

**Comment by istiti** [comment]
```
let result = this.dialogService.confirm('Voulez-vous vraiment supprimer: '+this.selectedFiles.nameFile, 'OUI', 'NON')
        result.then( choosedOption => {
            if(!!choosedOption){
                this.httpService.deleteDocument(this.selectedFiles.idfile).subscribe(resp => {
                    this.dataFiles.splice(this.selectedFiles.$$index, 1)
                })
            }
        });

This coosedOption == 1 when ESC, is it possible? I mean to me it is ! Am I doing some wrong or it's bug
```

**Comment by mseemann** [comment]
the function signature is:

```
  /**
   * Shows a dialog that is just a confirm message - e.g. with two button.
   * @param question The question that should be displayed.
   * @param declineText The text for decline button. defaults to Cancel
   * @param confirmText The text for the confirm button . defaults to Ok
   * @param vcRef The ViewContainerRef where the aletr dialog should be attached to.
   * Must not be provided if setDefaultViewContainerRef was set.
   * @returns A promise that is called if the user hits the Ok button.
   */
  public confirm(
    question: string,
    declineText = 'Cancel',
    confirmText = 'Ok',
    vcRef?: ViewContainerRef): Promise<ConfirmResult>
```

for your code it should be: dialogService.confirm('Voulez-vous vraiment supprimer: '+this.selectedFiles.nameFile, 'NON', 'OUI');

if my french is right :) the second parameter is the decline text the third the confirm text. this is equal to the order in the dialogs view.

**Comment by istiti** [comment]
You are right, I just realise that.
But it isn't my problem I speak about what choosedOption has (what the promise of result have) when I click on OUI I think I will receive number 1 instead of 0 and when I click  ESC or NON I wait 0, That was confusing me
Because now  ESC and NON give me 1
And OUI 0 inside result of promise (I don't speak about ConfirmResult.Confirmed)

**Comment by mseemann** [comment]
The number you see is just the internal value of the enum. Please checkout the dialog example: https://github.com/mseemann/angular2-mdl/blob/angular2-mdl-1.x/src/app/dialog/dialog.component.ts. There you see how to check the result in a typed way. We have typescript. We should use it where ever possible.

**Comment by istiti** [comment]
I understand what you mea, I just think instead of checking condition choosedOption with ConfirmResult.Confirmed,

It will be simplier to get us the right choose inside promise  arguement, so please apologize my english but I will try one more time,
In confirm dialog when I click **declineText** or **ESC** I except from promise

result.then( choosedOption => {
    //I except that choosedOption value is  0 (because 0 is falsy value) So you don't confirm so you receive FALSE value
});

But when I click on **confirmText** I except that choosedOption  === 1. because it's true.

I think we don't need compare choosedOption withn ConfirmResult.Confirmed

What do you think

**Comment by mseemann** [comment]
Pas de problème !

I have released this dialog api to get feedback from the users!  I don't like the implicit result that 0 is false. My intention was to use the enum value.

Instead of a result with a value i would then prefer to use then if the dialog is closed with confirm and if the user clicks cancel the promis should be rejected.
