### ISSUE TITLE
Get current tab 

### ISSUE THREAD

**Issue by icodenerd** [mseemann/angular2-mdl#1380]
Is there a way to get the current tab selected instead of the selected index instead?

**Comment by mseemann** [comment]
you can access the tabs property (https://github.com/mseemann/angular2-mdl/blob/master/src/lib/components/tabs/mdl-tabs.component.ts#L59) or query by yourself for the `MdlTabPanelComponents`. The active `MdlTabPanelComponent` `isActive` property (https://github.com/mseemann/angular2-mdl/blob/master/src/lib/components/tabs/mdl-tab-panel.component.ts#L36) is true.

**Comment by icodenerd** [comment]
Thanks for the tip! I got the current tab but when I am trying to get the title, the value always appears undefined even though it's showing in the browser just fine. I must be overlooking at something. Here's the TypeScript code snippet:

   this._currentTab = this.measurementTab.tabs.find(tab=>tab.isActive === true);
    let result = this._currentTab.title;

Here's how I bind data
 <mdl-tab-panel *ngFor="let loc of locations">
          <mdl-tab-panel-title>
            {{loc.Location}}
          </mdl-tab-panel-title>
          <mdl-tab-panel-content>
          </mdl-tab-panel-content>
        </mdl-tab-panel>

**Comment by mseemann** [comment]
may be your code runs before the the content was initialized (ngAfterContentInit). a plnkr would be great to help you checking this problem.
