### ISSUE TITLE
Angular 5 npm package version.

### ISSUE THREAD

**Issue by kokojvanko** [mseemann/angular2-mdl#1410]
First of all great package. We use it a lot and its one of the better ones out there. I can see that in master branch you have already upgraded to angular 5+, but there is no new NPM package available with those changes. The latest one 4.0.8 requires some peer deps that are lower than Angular 5 so i get some errors on that. Using master or forking unfortunately is not an option for me due to project related reasons. Any update would be greatly appreciated!

Thanks

**Comment by mseemann** [comment]
it's in the pipeline. for now you should see warnings but no error from npm regarding the peer dependencies.

**Comment by kokojvanko** [comment]
Cheers. Closing this as answered.
