### ISSUE TITLE
Dialog that starts animating from a specific element

### ISSUE THREAD

**Issue by andreialecu** [mseemann/angular2-mdl#143]
It would be nice if you could pass an $event to the modal open function so that the animation appears to pop-up from the button/link it is triggered by.

This would be pretty nice for a certain app I'm working on, as there are a lot of clickable items and the visual feedback would be good.

From what I can see, the Menu component already pops up from the `$event`, so having a modal start animating from there to the center of the screen doesn't seem necessarily hard to implement.  Not sure if angular2's animation provider can be used for this or it needs some custom JS animation code.

See here for what this should look like: https://material.angularjs.org/latest/demo/dialog

**Comment by mseemann** [comment]
menu is using css animation and a lot of direct style changes. dialog is using the angular2 animation dsl without touching the dom and styles directly. that's why the difference. 

need some time to think about it...

**Comment by mseemann** [comment]
published as angular2-mdl@2.3.0
