### ISSUE TITLE
Extended color schemes

### ISSUE THREAD

**Issue by c-martinez** [mseemann/angular2-mdl#1444]
At the moment, only `primary` and `accent` are allowed. Are there any plans to add extended color themes:

http://leifoolsen.github.io/mdl-ext/demo/color-themes.html

**Comment by mseemann** [comment]
unfortunately no. this package is based on getmdl.io - and there are only these two colors. also there is a full featured material design implementation for angular available now - so this package will only be mantained and I'm not going to implement new features.
