### ISSUE TITLE
'MdlDialogService' was not found in 'angular2-mdl'

### ISSUE THREAD

**Issue by luciantimar** [mseemann/angular2-mdl#159]
Using the latest version 2.2.0 when I try to use MdlDialogService I got ''MdlDialogService' was not found in 'angular2-mdl''
If I use declarative dialog everything works fine.
Any help will be appreciated.
Otherwise this is a great library that worked flawless from the beginning. Thank you

below some log from console window.

client?93b6:38[WDS] Warnings while compiling.
client?93b6:69C:/Work/Personal/SB/SW_Server/trunk/WebApps/Angluar2_Test1/sb2/src/app/hive/hive-card/hive-card.component.ts
49:354 export 'MdlDialogService' was not found in 'angular2-mdl'
Error: export 'MdlDialogService' was not found in 'angular2-mdl'
    at HarmonyImportSpecifierDependency.getWarnings (C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:34:14)
    at C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\lib\Compilation.js:640:21
    at Array.forEach (native)
    at C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\lib\Compilation.js:639:22
    at Array.forEach (native)
    at Compilation.reportDependencyWarnings (C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\lib\Compilation.js:638:9)
    at Compilation.<anonymous> (C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\lib\Compilation.js:497:8)
    at Array.forEach (native)
    at Compilation.finish (C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\lib\Compilation.js:496:15)
    at Compiler.<anonymous> (C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\lib\Compiler.js:434:15)
    at C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\tapable\lib\Tapable.js:152:11
    at Compilation.<anonymous> (C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\lib\Compilation.js:444:10)
    at C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\lib\Compilation.js:420:12
    at C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\lib\Compilation.js:332:10
    at C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\node_modules\async\lib\async.js:52:16
    at done (C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\node_modules\async\lib\async.js:246:17)
    at C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\node_modules\async\lib\async.js:44:16
    at C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\lib\Compilation.js:332:10
    at C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\node_modules\async\lib\async.js:52:16
    at done (C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\node_modules\async\lib\async.js:246:17)
    at C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\node_modules\async\lib\async.js:44:16
    at C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\lib\Compilation.js:332:10
    at C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\node_modules\async\lib\async.js:52:16
    at done (C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\node_modules\async\lib\async.js:246:17)
    at C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\node_modules\async\lib\async.js:44:16
    at C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\lib\Compilation.js:332:10
    at C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\node_modules\async\lib\async.js:52:16
    at done (C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\node_modules\async\lib\async.js:246:17)
    at C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\node_modules\async\lib\async.js:44:16
    at C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\lib\Compilation.js:332:10
    at C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\node_modules\async\lib\async.js:52:16
    at done (C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\node_modules\async\lib\async.js:246:17)
    at C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\node_modules\async\lib\async.js:44:16
    at C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\lib\Compilation.js:332:10
    at C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\node_modules\async\lib\async.js:52:16
    at done (C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\node_modules\async\lib\async.js:246:17)
    at C:\Work\Personal\SB\SW_Server\trunk\WebApps\Angluar2_Test1\sb2\node_modules\webpack\node_modules\async\lib\async.js:44:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

**Comment by mseemann** [comment]
the import must be: `import { MdlDialogService } from 'angular2-mdl';` if this is the case please give me some more information:
- which webpack version are you using?
- are you using MdlModule or MdlNonRootModule?
- contains the folder node_module/angular2-mdl the folder components? is there an index.js file and a lot of other folders?


normally this should work. the declarative components are using the MdlDialogService too...

**Comment by luciantimar** [comment]
I used `import { MdlDialogService } from 'angular2-mdl';` in component in which I want to display the dialog
I'm using MdlModule
I have created the application using angular cli tools. I don't now which version of webpack. If I'am looking on node_modules/webpack package.json, the version is "2.1.0-beta.22", 
The folder node_module/angular2-mdl seems to contain a lot of folders which include mdl-dialog-service.d.ts and js.

**Comment by luciantimar** [comment]
Meanwhile, I try to use a declarative dialog but I want to show it programmatic from component code and not from template definition?
`<mdl-dialog #editLogbookDialog [mdl-dialog-config]="{clickOutsideToClose: true, styles:{'width': '350px'}, isModal:true}"
	(show)="onDialogShow(dialogRef)" (hide)="onDialogHide()">
	<h3 class="mdl-dialog__title">Edit User</h3>
	<div class="mdl-dialog__content">
		<mdl-textfield type="text" label="Username" floating-label autofocus></mdl-textfield>
	</div>
	<div class="mdl-dialog__actions">
		<button mdl-button (click)="saveUser()" mdl-button-type="raised" mdl-colored="primary" mdl-ripple>Save</button>
		<button mdl-button (click)="editLogbookDialog.close()" mdl-ripple>Cancel</button>
	</div>
</mdl-dialog>`

How can I show this dialog from a component function ?

**Comment by mseemann** [comment]
acces from component:
@ViewChild('editLogbookDialog') private  editLogbookDialog: MdlDialogComponent;

You also find this in the code for the demo app: https://github.com/mseemann/angular2-mdl/tree/master/src/demo-app/app/dialog-declarative


for your build problem i have no solution. it looks everything right. So i guess it's a problem with your build pipeline. Here is a working demo repository with angular-cli and some angular2-mdl demo code including MdlDialogService (https://github.com/mseemann/a2-mdl-webpack). works without any problems.

**Comment by luciantimar** [comment]
I think I have found the problem.
The angular-cli version I used was angular-cli@1.0.0-beta.16 which was not the lastest version  (angular-cli@1.0.0-beta.17). 
I have upgraded angular-cli and everything works fine.
Thank you very much for your support.

**Comment by mseemann** [comment]
👍
