### ISSUE TITLE
mdl-color classes to textfield label

### ISSUE THREAD

**Issue by Aorewen** [mseemann/angular2-mdl#162]
Hi,

In MDL, we can change the color of a textfield label using the class mdl-color-text--{color}-{shade}.
How to do it with angular2-mdl syntax?

Thanks in advance,

**Comment by mseemann** [comment]
hi, right now there is no easy way. wether you need to override a lot of styles or you go back to the basics of getmdl.io and use the html snippets from there:

```
<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <input class="mdl-textfield__input" type="text" id="sample3">
    <label class="mdl-textfield__label" for="sample3">Text...</label>
  </div>
```
