### ISSUE TITLE
Support for Angular Universal

### ISSUE THREAD

**Issue by mseemann** [mseemann/angular2-mdl#168]
going to provide two modules. one that can be used on the server and client side and one that can only be used on the client side. why? because animation requires a lot of dom access that isn't possible on the server side.

**Comment by grizzm0** [comment]
Is it not possible to use the isNode and isBrowser from the universal package instead of providing two different modules?

**Comment by mseemann** [comment]
in this case this package would depend on angular2-universal. this is something i want to avoid. If someone uses universal it is usual to define two app modules. one for the server and one for the browser. i think it is not difficult to understand to include MdlServerModule instead of MdlModule. So the MdlServerModule can use mocks for functionality that isn't usual to use for prerendering on the server - for example dialogs (except the declarative ones)...

**Comment by hantsy** [comment]
Why not follow the Angular 2 packing naming? such as angular2-mdl and angular2-mdl/universal.


```
import MdlModule from 'angular2-mdl';
import MdlModule from 'angular2-mdl/universal';
```
