### ISSUE TITLE
cannot read forRoot of undefined

### ISSUE THREAD

**Issue by istiti** [mseemann/angular2-mdl#172]
Hi,
I try to use specific module of angular2-mdl and I get insignifiant error  when import MdlButtonModule: 
`Cannot read property 'forRoot' of undefined(…)`

I use it likethat in my bootstrap `app.module.ts`
```
    MdlIconModule.forRoot(),
    MdlLayoutModule.forRoot(),
    MdlTextFieldModule.forRoot(),
    MdlProgressModule.forRoot(),
    MdlDialogModule.forRoot(),
    MdlDialogOutletModule.forRoot(),
    MdlSpinnerModule.forRoot(),
    MdlButtonModule.forRoot(),
```
When I remove `MdlButtonModule `it works. 
Am I doing something wrong here ?

**Comment by mseemann** [comment]
can you show your complete app.module.ts? forRoot is a static function so it is really unlikely that MdlButtonModule is undefined...
