### ISSUE TITLE
readonly in typescript 2

### ISSUE THREAD

**Issue by a-jahanshahlo** [mseemann/angular2-mdl#182]
Hi, this accessor do not work on typescript 2.

`export declare class MdlBackdropOverlayComponent {
    clickEmitter: EventEmitter<any>;
    readonly display: string;
    private visible;
    private zIndex;
    onBackdropClick(e: any): void;
    hide(): void;
    showWithZIndex(zIndex: number): void;
}`

**Comment by mseemann** [comment]
Hi, this is intended. Have a look at https://github.com/mseemann/angular2-mdl/blob/master/src/lib/components/dialog-outlet/index.ts. 

Why do you need access to this component?
