### ISSUE TITLE
Wrong code in sample

### ISSUE THREAD

**Issue by urffin** [mseemann/angular2-mdl#192]
On page http://mseemann.io/angular2-mdl/tabs wrong code for "Baratheon" tab

Not shown list under this tab:

![image](https://cloud.githubusercontent.com/assets/8245171/20184130/b26d55aa-a778-11e6-9c7b-22ca0f0b4723.png)

Because in html, `ul` not inside `<mdl-tab-panel-content>`

![image](https://cloud.githubusercontent.com/assets/8245171/20184195/e4e6bcba-a778-11e6-800a-395197e83db7.png)

So, this bug in sample, if content always should be inside `<mdl-tab-panel-content>`, or bug in lib.

**Comment by mseemann** [comment]
hi, thx for submitting this. it is a bug in the sample. is fixed...
