### ISSUE TITLE
feat: Step in text fields

### ISSUE THREAD

**Issue by paullryan** [mseemann/angular2-mdl#201]
Step is an important feature of number type textfields that allows the field to validate against decimals without it you can't use type number to check something like 32.33.

**Comment by mseemann** [comment]
there is an html 5 attribute `step` for input type number fields (https://developer.mozilla.org/de/docs/Web/HTML/Element/Input). did you mean this attribute? If not is there an standard that covers this problem?

**Comment by paullryan** [comment]
Yes I mean that, and all I mean is adding support for it is see PR #203.

**Comment by paullryan** [comment]
Oh and you're too quick to respond sometimes :), I was trying to get the PR in before you had a chance ;-)

**Comment by mseemann** [comment]
thx for the pr! going to merge this into master. will be in the release on Friday.

quick? no ;-)
