### ISSUE TITLE
Using mdl-ripple anywhere

### ISSUE THREAD

**Issue by wsloth** [mseemann/angular2-mdl#214]
I have some elements like table rows (a `<tr mdl-ripple>`, not the `mdl-table`) that I want to ripple when clicked. I figured it's just a matter of adding the `mdl-ripple` directive on any element I want to ripple, but it seems it's not that easy.

I'm seeing [here](https://github.com/mseemann/angular2-mdl/blob/26bd53ee85d7a36183d91fabc02d2c5434db07d0/src/lib/components/common/mdl-ripple.directive.ts) that there are ripple directives defined for multiple types of mdl components.

Is it possible to have the mdl-ripple effect be a global directive, so I can use it on other elements as well?

**Comment by mseemann** [comment]
mdl-ripple adds additional span elements to the element with the mdl-ripple directive attached on. if  it would be possible to add mdl-ripple to a tr element this would result in invalid html (as far as i know only td/th elements can be a child of tr - thats one reason why this isn't a global directive). you may have reasons why you would add the ripple to the tr but i would suggest consider using mdl-list-item or use a checkbox to select a table row. it is also possible to add the mdl-ripple to a div. at least you can checkout the code how the ripple is applied (see mdl-ripple.directive.ts) and add this feature yourself. this should not be too difficult.

**Comment by wsloth** [comment]
I see. In that case I'll use a simple CSS click effect.

The reason I wanted to add it is because I have a table with a lot of data that shows a modal when the entire row is clicked, which would look nicer with the ripple click effect.

Thanks for the explanation!
