### ISSUE TITLE
AOT fail

### ISSUE THREAD

**Issue by daniele-zurico** [mseemann/angular2-mdl#216]
Hi I'm trying to compile in Aot mode but it fail for that reason:
```
angular2-mdl/components/dialog-outlet/mdl-backdrop-overlay.component.ngfactory.ts:48:39 
Property 'zIndex' is private and only accessible within class 'MdlBackdropOverlayComponent'
```

I'm using 2.4.1

This is just an example but actually most of them fail.
The reason is that: things that the template accesses from the component **must** be public

**Comment by mseemann** [comment]
thx. will be fixed and will be in the release tomorrow...

**Comment by daniele-zurico** [comment]
please do it :) I'm one step to have AOT ready just waiting you guys :)

**Comment by mseemann** [comment]
nice! i knew this is hard :)

**Comment by daniele-zurico** [comment]
Sorry guys but mine was just an example there really a lot of them

**Comment by mseemann** [comment]
right now i have no idea how i could test that i do not miss any aot problems. do you have  a list? i have only checked the properties with HostBinding..

**Comment by mseemann** [comment]
what is your env? angular-cli? which version? angular2 version?

**Comment by daniele-zurico** [comment]
The version is 2.1.2 what I did is including in my app the materialModule. Not using the cli but my environment and unfortunately I don't have the list atm. I can try to do tomorrow morning but the rule is super easy. Everything that you declare in your class and will be used in your template have to be public

**Comment by mseemann** [comment]
a list would be great! also i would appreciate to see how you setup your project - i have a test project for cli that didn't had these problems with angular@2.1.2...

**Comment by mseemann** [comment]
please check against version 2.4.3. the list is hopefully empty or even smaller...

**Comment by daniele-zurico** [comment]
hey thanks a lot unfortunately there're still private var around.
Is much easier if I fork the project I fix them and I create a PR. 
I'll let you know.

**Comment by mseemann** [comment]
👍 
this is a little bit strange because my test project works  with aot (https://github.com/mseemann/a2-mdl-webpack and live: http://mseemann.io/a2-mdl-webpack/) We'll see...

**Comment by ulic75** [comment]
I'm using angular2-mdl 2.6.0 and compiling AOT with angular-webpack2-starter.  I'm receiving numerous private property errors and also numerous "Supplied parameters do not match any signature of call target." errors.  You can find my list at http://pastebin.com/zuMp8PEh.  I'm a bit of a coding novice, but if you have questions I'll answer as best I can.

**Comment by mseemann** [comment]
afaik angular-webpack2-starter did not support aot: https://github.com/AngularClass/angular2-webpack-starter/issues/885

**Comment by ulic75** [comment]
Show what a n00b I am.  Apparently I'm using this repo fork and didn't realize it was a fork.

https://github.com/qdouble/angular-webpack2-starter
