### ISSUE TITLE
mdl-textfield not getting focus on click, when value pre-set

### ISSUE THREAD

**Issue by stanislasdrg** [mseemann/angular2-mdl#231]
**Current behavior**
I am setting an mdl-textfield text through ng-model when my app starts.
The textfield has a floating label.
After load, if I try to edit the input text by clicking at the end of the line the cursor doesn't appear. The field is in edit mode though, and I can enter and delete values correctly. 
If I click on the pre filled word itself, the cursor appears, but if I delete a character, it deletes the n-2 one instead of the n-1.
Everything works as expected in Safari and Firefox.

The code : 
`      <mdl-textfield type="text" label="Primary Owner" [(ngModel)]="owner1" name="owner" floating-label></mdl-textfield>`

**Expected behavior**
The cursor should become visible when clicking anywhere on the text field.

Environment:
MBP under MacOs Sierra, Angular2 Typescript with Webpack (Angular-cli).
Angular version : 2.1.2
Angular router version : 3.1.0

Browser:
Chrome 54
Language:
Typescript 2, Es6
Node (for AoT issues): node --version = 6.0.42

**Comment by mseemann** [comment]
hi. can you create a simple plnkr for this issue. here is a template: http://plnkr.co/edit/I3dLfLUDIH2xlEJqj0da?p=preview. thx!

**Comment by stanislasdrg** [comment]
Must be a problem with my code, because it is working fine in plunker.
Whoever I am using resolvers and displaying components when my data has finished loading.
Will investigate and update. Thanks !

**Comment by mseemann** [comment]
👍

**Comment by mseemann** [comment]
Closing this for now. We can reopen the issue if needed...

**Comment by stanislasdrg** [comment]
Ah it turned out that the css code below provoked this odd behaviour : 
```
mdl-textfield:first-letter {
  text-transform:capitalize;
}
```

Thanks for your help !

**Comment by mseemann** [comment]
👍
