### ISSUE TITLE
Show/close tooltip

### ISSUE THREAD

**Issue by Stoope** [mseemann/angular2-mdl#235]
Is there any way to show/close tooltip from code, not only onmouseover/onmouseleave?

**Comment by mseemann** [comment]
not yet. can you explain your usecase for this feature?

**Comment by Stoope** [comment]
I want to show error message over input field

**Comment by mseemann** [comment]
i can expose show and hide on mdl-simple-tooltip and mdl-tooltip. for show you'll need to provide an html element to calculate the tooltip position. would this be sufficient?

**Comment by Stoope** [comment]
Yes, it would be great.

**Comment by mseemann** [comment]
ok

**Comment by mseemann** [comment]
published as 2.5.0. how to use it: http://mseemann.io/angular2-mdl/tooltip at the end of the page.
