### ISSUE TITLE
input label does not animate (nor gets hidden when no placeholder is present)

### ISSUE THREAD

**Issue by moshmage** [mseemann/angular2-mdl#239]
The following code will work, but "Search books..." will remain seen even after the user starts typing.
The same isn't true if we provide a `placeholder="type text here"` prop - but it will instead render `label` prop useless as it will never show up nor animate.

```html
<mdl-textfield
  type="text"
  label="Search books..."
  (keyup)="search($event.target.value)"
  placeholder=""
  autofocus
  autocomplete="name"
  (blur)="onBlur($event)"
  (focus)="onFocus($event)">

</mdl-textfield>
```

**Comment by mseemann** [comment]
hi. can you create a plnkr that shows both cases. here is a template: http://plnkr.co/edit/I3dLfLUDIH2xlEJqj0da?p=preview  thx!

**Comment by moshmage** [comment]
@mseemann hey no problemo, here it is http://plnkr.co/edit/i9PgPD5RbKzOSqEaQiRN?p=preview (the "label" and "placeholder" props are self-explainable ;) )

**Comment by mseemann** [comment]
I'm afraid what you are trying to do isn't possible with mdl. see the modified plnkr: http://plnkr.co/edit/H66coqQFku0MnOBTx6BR?p=preview. If you define both (placeholder and label) you need to also set floating-label. mdl is then showing the placeholder and the label. 

did i miss something what you are trying to do?

**Comment by moshmage** [comment]
Oh! Yep. My bad indeed. You da man!
