### ISSUE TITLE
mdl-button and ngFor ereases spacing between buttons 

### ISSUE THREAD

**Issue by moshmage** [mseemann/angular2-mdl#247]
I'm not sure it "erases" or if adding a button outside of an ngFor *adds* spacing as I'm not really sure what are the specs on spacing between buttons.

this is "fixed" by `:host .mdl-button { margin-right: 4px }` .. yes. `4px` hence why I'm now doubting if it's the browser adding a space OR if its really the default - because for some reason, the non-ngFor button *has no margin propreties* in the computed styling.

[reproduction in plunkr](http://plnkr.co/edit/rsIZgOzIyH25sTBnSHOr)

*I updated the [plunkr*](http://plnkr.co/edit/rsIZgOzIyH25sTBnSHOr) to have the demo of the margin. though now the last element feels a little bit... off. I think it's because `::last-child` is not catching on - but it serves its propose.*

It's just something that was flickering my eye for a few hours now. I had to share the pain.

**Comment by moshmage** [comment]
I updated the [plunkr*](http://plnkr.co/edit/rsIZgOzIyH25sTBnSHOr) to have the demo of the margin. though now the last element feels a little bit... off. I think it's because `::last-child` is not catching on - but it serves its propose.

**Comment by mseemann** [comment]
mld sets the mdl-button to display: inline-block. if you have any whitespace between inline-block elements they have a small gap if you put them next to each other without a whitespace there is no gap (ngFor did exactly that). see for example: http://stackoverflow.com/questions/16678929/display-inline-block-what-is-that-space

a possible solution is using ng-container:

          <ng-container  *ngFor="let option of ['hello', 'world', 'nopadding?']; let i = index">
              <button mdl-button mdl-ripple mdl-button-type="raised" mdl-colored="accent" class="mm-text__capitalize"
              (click)="toggleOption(i)">{{option}}</button>
          </ng-container>
