### ISSUE TITLE
Question: Can you set mdl-layout-drawer width

### ISSUE THREAD

**Issue by LukeHartcher** [mseemann/angular2-mdl#265]
I would like to make the mdl-layout-drawer wider, is it possible to customise this? I tried to override as per below, but then the drawer does not close completely and the additional width is still displayed.

```
.mdl-layout__drawer {
  width: 500px;
}
```

![image](https://cloud.githubusercontent.com/assets/1154551/20772797/0959b180-b7a3-11e6-8a37-6ebc37b5f769.png)

**Comment by mseemann** [comment]
this is possible if you are using the scss sources. just change the variable that is responsible for the width. for example:
 $layout-drawer-width: 350px;
@import '~angular2-mdl/scss/material-design-lite';

**Comment by LukeHartcher** [comment]
Perfect! (I just found this and hacked the mdl/_variables.scss but overriding is great)

Thanks for the prompt response!!
