### ISSUE TITLE
mdl-layout-header-transparent not working?

### ISSUE THREAD

**Issue by LukeHartcher** [mseemann/angular2-mdl#266]
Trying to use mdl-layout-header-transparent however the header is showing a white box, even though the CSS says transparent. I have tried to use the sample layout but cannot get that working.

```
<mdl-layout mdl-layout-fixed-drawer>
  <mdl-layout-header mdl-layout-header-transparent>
      <mdl-layout-header-row>
        <nav class="mdl-navigation">
            <button mdl-button #btn1="mdlButton" (click)="m1.toggle($event, btn1)" mdl-button-type="icon" mdl-ripple><mdl-icon>account_circle</mdl-icon></button>
            <mdl-menu #m1="mdlMenu" mdl-menu-position="bottom-right">
            <mdl-menu-item mdl-ripple><mdl-icon>lock_outline</mdl-icon> Login</mdl-menu-item>
            <mdl-menu-item mdl-ripple><mdl-icon>lock_open</mdl-icon> Logout</mdl-menu-item>
          </mdl-menu>
        </nav>
      </mdl-layout-header-row>
  </mdl-layout-header>
  <mdl-layout-drawer>
      <mdl-layout-title>{{title}}</mdl-layout-title>
      <app-filter></app-filter>
  </mdl-layout-drawer>
  <mdl-layout-content>
    <app-map></app-map> 
    <router-outlet></router-outlet>
  </mdl-layout-content>
</mdl-layout>
```

![image](https://cloud.githubusercontent.com/assets/1154551/20774959/cbcae82a-b7ac-11e6-8f79-314088918796.png)

CSS is setting to transparent.

![image](https://cloud.githubusercontent.com/assets/1154551/20775002/f96f5090-b7ac-11e6-82a8-3f83ffe16b63.png)

But the content div is being pushed down by the header..

![image](https://cloud.githubusercontent.com/assets/1154551/20775063/3b705548-b7ad-11e6-8ad3-cf00888ef10b.png)

What am I doing incorrectly?

**Comment by mseemann** [comment]
sorry. this is a little bit to much information for a quick answer. usually mdl-layout-header-transparent works - see the demo. i guess you have added something that conflicts. would be great if you could provide a minimal plnkr that reproduces your problem. (template: http://plnkr.co/edit/I3dLfLUDIH2xlEJqj0da?p=preview). even better: i think questions like this are perfect for stackoverflow.

**Comment by LukeHartcher** [comment]
I am trying to use it in combination with https://angular-maps.com/ so it could very well be that. I have disabled the header to get full screen map working to get around my problem. If I still cannot resolve I will raise on SO. Cheers.

**Comment by mseemann** [comment]
👍
