### ISSUE TITLE
Snackbar not working

### ISSUE THREAD

**Issue by leolorenzoluis** [mseemann/angular2-mdl#273]
Using Safari 10.0.1 with macOS.

Clicking the snack bar button doesn't do anything.

**Comment by mseemann** [comment]
a plknr please (template: http://plnkr.co/edit/I3dLfLUDIH2xlEJqj0da?p=preview)

**Comment by leolorenzoluis** [comment]
How do I inject `MdlSnackbarService` in plunker?

**Comment by mseemann** [comment]
please have a look at the browser console. there is an error message wth a link how to fix the problem. thx.

**Comment by leolorenzoluis** [comment]
Updated http://run.plnkr.co/qY7z37X2r9ayJaBm/ 

Basically, I found the error when trying it from your demo app.

**Comment by mseemann** [comment]
ok. works for me in chrome and safari. ??

**Comment by leolorenzoluis** [comment]
Found the culprit. An adblock extension blocks it.

**Comment by mseemann** [comment]
interesting. which url did it block?

**Comment by leolorenzoluis** [comment]
Not sure, any tips how I can find that out?

**Comment by mseemann** [comment]
usually in the network tab of the browser console. there must be some url that are blocked...

**Comment by leolorenzoluis** [comment]
Can't seem to find it, if you could help me find it, I'll be happy to submit a PR. 👍
