### ISSUE TITLE
Radio rendering bug in Safari (mac os el capitan)

### ISSUE THREAD

**Issue by Harper04** [mseemann/angular2-mdl#277]
Hi,

i found a rendering bug in the radio component. You can test it here using Safari 
http://mseemann.io/angular2-mdl/toggle (and on every other page using radios)

It happens if you select a previously unselected radio. The whole viewport flickers blue.

The vanilla getmdl.io demo does not seems to have this issue.

best regards

Tom

**Comment by mseemann** [comment]
it was 'only' a build problem for the demo site.
