### ISSUE TITLE
Consecutive snackbars Specs is mismatched from Google Material Specs

### ISSUE THREAD

**Issue by ZafarSaeedKhan** [mseemann/angular2-mdl#283]
There is only ever one snackbar displayed. When a second snackbar is triggered while the first is displayed, the first should start the contraction motion downwards before the second one animates upwards.
https://material.google.com/components/snackbars-toasts.html#snackbars-toasts-usage

**Comment by ZafarSaeedKhan** [comment]
#286 
Here is my proposed fix

**Comment by mseemann** [comment]
fixed
