### ISSUE TITLE
Timeout not working if provided with the Action

### ISSUE THREAD

**Issue by ZafarSaeedKhan** [mseemann/angular2-mdl#284]
**Current Behaviour:**
When _Timeout_ is provided with the _Action handler_ then it simply ignores the _Timeout_ and waits for the _Action_.

**Expected Behaviour:**
According to _Google Material Design Specs_ if _Timeout_ is not provided then it will automatically hide it self after default Timeout or do whatever is defined in the _Action handler_, whichever is first.

**Comment by ZafarSaeedKhan** [comment]
#285

**Comment by mseemann** [comment]
fixed.
