### ISSUE TITLE
Tristate checkbox

### ISSUE THREAD

**Issue by ZafarSaeedKhan** [mseemann/angular2-mdl#287]
I have a requirement of tristate checkbox, so can I expect a solution from your side on this issue or can I propose a solution for it?

**Comment by mseemann** [comment]
hi. a tree state checkbox is not part of material design lite v1.x - so it will not be in this package. there is an https://github.com/mseemann/angular2-mdl-ext package that has not this restriction. if you want you can propose a solution there.

**Comment by ZafarSaeedKhan** [comment]
Ok i will propose my solution soon for this issue in the https://github.com/mseemann/angular2-mdl-ext package
