### ISSUE TITLE
Confirmation dialog with Heading

### ISSUE THREAD

**Issue by ZafarSaeedKhan** [mseemann/angular2-mdl#300]
There is frequent need of Header in the confirm dialog box.
There must be an option in confirm dialog to provide Header title in the confirm dialog box.
Can you provide a solution for this can I propose a solution?

**Comment by mseemann** [comment]
did you mean a title like it is present for the alert dialog?

**Comment by ZafarSaeedKhan** [comment]
Yeah like alert dialog

**Comment by mseemann** [comment]
ok. go ahead! 👍

**Comment by ZafarSaeedKhan** [comment]
#312 
Here is my proposed solution.

**Comment by mseemann** [comment]
Fixed
