### ISSUE TITLE
How to use this for non-root module?

### ISSUE THREAD

**Issue by khatv911** [mseemann/angular2-mdl#304]
I got an template parse error once using this with sub module's component. Please help, thanks a lot.

**Comment by mseemann** [comment]
there is also a MdlNonRootModule in this package. have you tried this? if this dosen't help please create a plnkr that demonstrates your problem. thx.

**Comment by khatv911** [comment]
@mseemann: could you guide me? i already did this:
`@NgModule({
    id: 'MenuModule',
    imports: [CommonModule, FormsModule, MdlNonRootModule],
    exports: [MenuComponent, MenuItemComponent],
    declarations: [MenuComponent, MenuItemComponent],
    providers: [],
})
export class MenuModule { }`

**Comment by mseemann** [comment]
seems ok. what error do you get?

**Comment by khatv911** [comment]
@mseemann : that was silly of me, i duplicated one line <mdl-***> in the layout. Truly sorry and thanks for your support.

**Comment by mseemann** [comment]
never mind!
