### ISSUE TITLE
Problem with mdl-text-field__error

### ISSUE THREAD

**Issue by PhilippeCorreges** [mseemann/angular2-mdl#308]
Hello,
I use a mdl-text-field__error and see that when I enter a value with wrong value according to regexp, the error is not shown.
Here is a [code pen](https://codepen.io/PhilippeCorreges/pen/JbBYPO)

**Comment by mseemann** [comment]
please create a plnkr (http://plnkr.co/edit/I3dLfLUDIH2xlEJqj0da?p=preview) that uses angular2-mdl. your example uses the plain css classes from getmdl.io - this won't work.

**Comment by PhilippeCorreges** [comment]
Hi @mseemann 
In the plunker you have 

> <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://code.getmdl.io/1.2.1/material.light_blue-amber.min.css" />

and in my codepen I have : 

`<link` href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
`<link` rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
<link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.indigo-pink.min.css" />
<meta name="viewport" content="width=device-width, initial-scale=1">

I really do not understand well your answer. Should I use other classes  like <mdl-textfield type="text" label="Text..." [(ngModel)]="text3" floating-label></mdl-textfield>

In that case, something is still not clear : We use the same css and we have to write different tags than the ones written on getmdl.io ... even if we are using their css ...

Thanks. I would be happy for a clarification.

**Comment by mseemann** [comment]
you need to use the angular components from angular2-mdl. if you don't use these components you get styled html elements without any functionality.

**Comment by PhilippeCorreges** [comment]
thanks @mseemann
