### ISSUE TITLE
Question : Is there any Footer ?

### ISSUE THREAD

**Issue by PhilippeCorreges** [mseemann/angular2-mdl#309]
Hello,
I have not seen anything like <mdl-layout-footer>

Does it exist something like that ? It is just a "FYI".

Kind regards

**Comment by mseemann** [comment]
hi. no there are no special footer components. for footer styling please use the original css from mdl: https://getmdl.io/components/index.html#layout-section/footer

**Comment by PhilippeCorreges** [comment]
thanks @mseemann
