### ISSUE TITLE
Update readme to rc5 and webpack support?

### ISSUE THREAD

**Issue by goelinsights** [mseemann/angular2-mdl#31]
Looks like latest version in master is Angular RC5, but readme indicates otherwise.  Is RC5 supported?

Also, documentation is for systemJS.  Is webpack supported?

**Comment by mseemann** [comment]
yes, I am working on the upgrade to rc5. the npm package 1.2.0 is still using rc4.

webpack will also come with the next release (1.3.0)

I will close this issue if ti's done...

**Comment by mseemann** [comment]
done. good luck :-)
