### ISSUE TITLE
Auto expand textfield

### ISSUE THREAD

**Issue by baole** [mseemann/angular2-mdl#318]
I use mdl-textfield for user's text input. I want to start an text area with 3 lines and automatically expand as user inputs (see below code).  The problem is that mdl-textfield is not expanding. maxrows attributes does not help. Any suggestion?

```
        <mdl-textfield
                type="text"
                rows="3"
                [(ngModel)]="explain"
                floating-label
                label="Explain"></mdl-textfield>

```

**Comment by mseemann** [comment]
Please create a plnkr that demonstrates your problem. Thx!

**Comment by baole** [comment]
Here is an example: http://plnkr.co/edit/6Hz5Br?p=preview

**Comment by mseemann** [comment]
ok. i understand. this will not work out of the box with mdl (see https://getmdl.io/components/index.html#textfields-section) so it will not work with angular2-mdl.
