### ISSUE TITLE
Support custom layout-screen-size-threshold in mdl-layout

### ISSUE THREAD

**Issue by matthiasscudlik** [mseemann/angular2-mdl#329]
Please add the support for a custom screen size treshhold in mdl-layout.
Currently i can change the sass variable layout-screen-size-threshold to my desired value, but in the layout component a hard coded value is used to detect if a small screen is used. [see sass variable here](https://github.com/mseemann/angular2-mdl/blob/master/src/lib/scss/mdl/_variables.scss#L390) and [hard coded value here](https://github.com/mseemann/angular2-mdl/blob/master/src/lib/components/layout/mdl-layout.component.ts#L152)
Changing only layout-screen-size-threshold leads to a mobile layout where the layout-drawer is still shown.

Using bootstrap4 for example, 768px is used as a treshhold/breakpoint and you cannot get a common look and feel this way.

Thanks a lot for your great work and best regards,
Matthias

**Comment by mseemann** [comment]
will works as follow:

```
/ * The LAYOUT_SCREEN_SIZE_THRESHOLD can be changed at the root module. Just provide a value for this OpaqueToken:
 *
 * providers: [
 *  {provide:LAYOUT_SCREEN_SIZE_THRESHOLD, useValue: 768 }
 * ]
 *
 * you also need to change the scss variable to the same value: $layout-screen-size-threshold: 768px.
*/
export const LAYOUT_SCREEN_SIZE_THRESHOLD = new OpaqueToken('layoutScreenSizeThreshold');
```
