### ISSUE TITLE
Mdl-menu getting clipped inside mdl-card

### ISSUE THREAD

**Issue by leolorenzoluis** [mseemann/angular2-mdl#340]
Given the plunker:

http://plnkr.co/edit/wnQ0RzH47cU2gMWfNjZf?p=preview

Using native MDL:

http://codepen.io/tutsplus/pen/RWwypM

The codepen one works as expected. However, angular2-mdl looks like is getting clipped.

**Comment by mseemann** [comment]
in the codepen one you have positioned your menu to be completely inside the card. if you change the position from mdl-menu--bot-right to mdl-menu--bottom-right you got the same result - the menu is clipped.

**Comment by leolorenzoluis** [comment]
Hmm, I'm no css expert, but does that mean I have to move away from using mdl card with menu together as it looks like the mdl card are box-sized and clipped whatever content of its child?

**Comment by mseemann** [comment]
no. you can try to put the menu outside the card html structure. so that is not a child of the card.

**Comment by leolorenzoluis** [comment]
Could you please show me a simple example? Does this involve hacking around the margin/padding of the menu, so that it would look like it's inside the mdl-card?

**Comment by mseemann** [comment]
sorry this will not work. if i change the dom position the menu is no longer in position with the button :(

but you can change the style for the mdl-card. right now it is overflow:hidden - if you change this to overflow visible the menu is full visible.

**Comment by leolorenzoluis** [comment]
What's the next step CSS hack to prevent this? http://plnkr.co/edit/mSYr8YZMOfxWHnZMABZE?p=preview

It's still clipping. :(

**Comment by mseemann** [comment]
i can't see any HACK. it's the way dom and css work. now your z-order is the stumbling block.
