### ISSUE TITLE
package renaming for agular 4

### ISSUE THREAD

**Issue by mseemann** [mseemann/angular2-mdl#341]
the next major release of angular will be 4.X. So the name of this package (angular**2**-mdl) isn't suitable anymore. The package for angular4 will be **@angular-mdl/core** and the ext packages will be under @angular-mdl (e.g **@angular-mdl/popover** and **@angular-mdl/select**).

**Comment by mseemann** [comment]
@angular-mdl/core is already available in beta and works with angular 4 rc.1

**Comment by mseemann** [comment]
done!
angular2-mdl -> @angular-mld/core
@angular2-mdl-ext/popover -> @angular-mdl/popover
@angular2-mdl-ext/select -> @angular-mdl/select
@angular2-mdl-ext/expansion-panel -> @angular-mdl/expansion-panel

all packages have been upgraded to angular 4 rc.3
right now only the expansion-panel has some problems with this upgrade.

**Comment by bsh314** [comment]
Hi Michael. Currently i'm trying to update my project from angular2 to angular4, but after spending some time getting rid of the new errors, there are many(20+) errors like those in mdl directives/components: 

```
ERROR in /home/bshcherbak/Projects/emergya/node_modules/angular2-mdl/components/common/mdl-ripple.directive.d.ts (1,78): Cannot find module '@angular/core'.

ERROR in /home/bshcherbak/Projects/emergya/node_modules/angular2-mdl/components/badge/mdl-badge.directive.d.ts (1,70): Cannot find module '@angular/core'.

ERROR in /home/bshcherbak/Projects/emergya/node_modules/angular2-mdl/components/button/mdl-button.component.d.ts (1,70): Cannot find module '@angular/core'.

ERROR in /home/bshcherbak/Projects/emergya/node_modules/angular2-mdl/components/card/mdl-card.component.d.ts (1,45): Cannot find module '@angular/core'.

ERROR in /home/bshcherbak/Projects/emergya/node_modules/angular2-mdl/components/checkbox/mdl-checkbox.component.d.ts (1,73): Cannot find module '@angular/core'.
.
.
.
```
I've re-installed packages, changed all imports & searched for errors in @angular-mdl/core/components. Nothin of that helped. Some advice?

**Comment by mseemann** [comment]
hi. please remove the folder angular2-mdl from you node_modules (npm prune should do this) and from you package.json. run npm install @angular-mdl/core --save and replace all imports from 'angular2-mdl' to '@angular-mdl/core'. If you need a working example: https://github.com/mseemann/angular-mdl-a4-angular-cli.
