### ISSUE TITLE
Support for Electron

### ISSUE THREAD

**Issue by crystalraebryant** [mseemann/angular2-mdl#342]
# Request
I've used this library in an Angular app already, and would love to use it while developing an Angular app with Electron.

# Issue
Right now, when attempting to implement angular2-mdl in an Electron Angular app with Webpack, it generates this error:

`Uncaught TypeError: ctorParameters.map is not a function`

# Replicate
1. Clone the [angular2-electron-starter](https://github.com/cmelo/angular2-electron-starter) project.
2. Install angular2-mdl.
3. Add MdlModule to the @NgModule imports.
4. Follow the angular2-electron-starter steps to run the application.
5. See error in Chrome console.

**Comment by mseemann** [comment]
hi. i don't have time to investigate this issue. would be really great if you could find the reason for the problem and provide a pr for that.

**Comment by crystalraebryant** [comment]
I definitely hope to dig into this more. I haven't found any documentation on anyone else running into it. If I figure it out, I'll definitely submit a pr.

**Comment by mseemann** [comment]
👍

**Comment by paullryan** [comment]
@mseemann This also effects universal with 2.1.1 which I know you're working towards (just a heads up). It appears to be something deep in a refactor with the 2.1.x series in the Reflection code for DI.

**Comment by mseemann** [comment]
sounds reasonable. i've taken a look at the package.json. the angular version can move up but the angular-cli version is fixed to an outdated version. there are lot of problems if one is not using the angular version angular-cli is designed for. i don't know what the expected angular version for angular cli beta 18 is. also a point for many problems is aot compilation - do you know wether angular2-electron-starter is using aot or not?

**Comment by paullryan** [comment]
Sorry I don't know, I did figure out too that if I don't use your packed version (e.g. I pull the source directly into my universal project) this issue goes away.

**Comment by nikoTM** [comment]
>Uncaught TypeError: ctorParameters.map is not a function

This error is caused by [in-memory-web-api](https://github.com/angular/in-memory-web-api), to solve the issue simply update to angular@1.0.0-beta.22-1 (implying angular ~2.2).

**Comment by mseemann** [comment]
@crystalraebryant you can use the electron starter if you fix the angular2-mdl version to 2.7.0. if you are using a newer version you need to upgrade the stater project to angular 2.4.1 and angular-cli beta 24. the reason is: newer versions of angular2-mdl are always compiled with the latest angular-compiler version. here is a project that uses the latest versions: https://github.com/mseemann/angular2-mdl-electron-starter. it works. I have added some mdl buttons to demonstrate it.
