### ISSUE TITLE
mdl-checkbox does not set 'checked' property

### ISSUE THREAD

**Issue by stepanzarubin** [mseemann/angular2-mdl#361]
Hi, I need to set `checked` property for the input based on custom check without ngModel:

```
<mdl-checkbox [checked]="satisfyLogic ? true : false" (change)="toggleCustom()">Checkbox</mdl-checkbox>
```

Which gives me an error:
```
Can't bind to 'checked' since it isn't a known property of 'mdl-checkbox'
```

I tried this as well:
```
[ngClass]="{'is-checked': satisfyLogic ? true : false}"
```

MDL clearly sets `checked` property for the input [#toggles-section](https://getmdl.io/components/#toggles-section) while `angular2-mdl` is not.

Thanks in advance.

**Comment by stepanzarubin** [comment]
This worked for me:

```
<mdl-checkbox [ngModel]="satisfyLogic ? true : false" ....
```

But I am not sure if this correct way to do it. Originally I thought that `ngModel` works only with defined component properties.

**Comment by mseemann** [comment]
hi. there is no checked property because the checked state is covered by ngModel. if you only need a checked state without a component property (or reactive forms property) you can do it like in your example.

**Comment by stepanzarubin** [comment]
Thanks! I need to set checked state only once.
