### ISSUE TITLE
mdl-textfield and forms

### ISSUE THREAD

**Issue by aleksfes** [mseemann/angular2-mdl#37]
Hi!

Is mdl-textfield compatible with [angular/forms](https://angular.io/docs/ts/latest/guide/forms.html)?
Is there a way to pass name and id attributes to the input element?

These code:
```html
<form (ngSubmit)="generate(reportForm.value)">

<mdl-textfield type="text"
    label="IDs"
    [(ngModel)]="reportParams.userIds"
    floating-label
    ngControl="userIds"
    name="userIds"
    required
></mdl-textfield>


</form>
```
produces error:
```
vendor.js:43701 EXCEPTION: Error: Uncaught (in promise): No value accessor for form control with name: 'userIds'
```

Maybe, I'm doing something wrong.
npm: Angular2 rc5, angular/forms 0.3.0, angular2-mdl 1.3.0.

**Comment by gibsonsyd** [comment]
add #userIds ="ngModel" to the mdl-textfield attributes

**Comment by aleksfes** [comment]
@gibsonsyd , thanks a lot!

This worked:
```html
<mdl-textfield type="text"
    label="ID пользователей"
    [(ngModel)]="reportParams.userIds"
    #userIds="ngModel"
    name="userIds"
    required
    floating-label
></mdl-textfield>
```

**Comment by mseemann** [comment]
@gibsonsyd thx for your help.

**Comment by BrentDietrich** [comment]
Hi, 

Is their a way to use the MdlTextFieldComponent with model-driven forms that use formControlName rather than [(ngModel)]? 

npm: Angular2 rc5, angular/forms 0.3.0, angular2-mdl 1.3.0.

**Comment by mseemann** [comment]
hi,
yes it is. you need to import both modules (FormsModule, ReactiveFormsModule) in your app module. Please have a look at: http://mseemann.de/angular2-mdl/reactiveForms. I added an example on how to use this.

**Comment by BrentDietrich** [comment]
Thank you, I'll take a look at the docs.
