### ISSUE TITLE
Can't retrieve data from a custom dialog passed along to the `hide(data?: any` method in `MdlDialogReference`

### ISSUE THREAD

**Issue by internetjesus** [mseemann/angular2-mdl#394]
I'm implementing a custom option select dialog which shows a few options in a list along with checkboxes. The goal I'm trying to achieve is to get the selected option back in the host component that initiated the custom dialog. 

In `mdl-dialog.service.ts` the hide method has an optional data (data? any) parameter that is passed along to the `InternalMdlDialogReference` hide method so I thought I could just call the hide method and pass the user selected data along with it. 

However, and here lays the problem I think, the onHide method which returns the onHideSubject has an `void` typing on it. This means I can't get the data passed in to hide(data?: any) . method in my host component subscription.

**Comment by mseemann** [comment]
Please provide a plnkr that shows your intentional use case. Thx.

**Comment by internetjesus** [comment]
Seeing that this is more of a question, I will ask it on Stackoverflow instead.
