### ISSUE TITLE
scrolling issue with the context menu

### ISSUE THREAD

**Issue by shahbazshueb** [mseemann/angular2-mdl#409]
When the context-menu is open in a scrollable content then the menu also scrolls down instead of staying fixed at its position.

![context menu scroll problem](https://cloud.githubusercontent.com/assets/10958507/21763897/1ffa4abe-d682-11e6-9420-a2c8b84bc4e5.PNG)

**Comment by mseemann** [comment]
hi, please provide a plknr for your issue. thx.

**Comment by shahbazshueb** [comment]
Sorry, created this issue by mistake. It was supposed to be created on another repo.
