### ISSUE TITLE
How to make maxlength working for textfields?

### ISSUE THREAD

**Issue by stepanzarubin** [mseemann/angular2-mdl#433]
Both of these does not work:
```
<mdl-textfield type="text""maxlength"="4"></mdl-textfield>
<mdl-textfield type="text" [maxlength]="4"></mdl-textfield>
```
I need this for string field, not a number.
Thanks.

**Comment by mseemann** [comment]
https://github.com/mseemann/angular2-mdl/issues/397 will be released tomorrow...
