### ISSUE TITLE
required validation error displaying immediately

### ISSUE THREAD

**Issue by kevfuzz** [mseemann/angular2-mdl#439]
Hi,

Not sure if I've used it right but I've added 'required' to an input field and I can see my validation message. However the message is displayed even before the field is touched...is this correct? Is there any way to wait till the field is touched before displaying the validation message?

Thanks,
Kevin.

**Comment by mseemann** [comment]
hi. this behavior is intended. please have a look at http://stackoverflow.com/questions/40678771/how-to-show-the-error-message-of-a-mdl-textfield-programmatically for information on how to set error messages programmatically.
