### ISSUE TITLE
MdlRadioComponent problem

### ISSUE THREAD

**Issue by Boichenko** [mseemann/angular2-mdl#444]
Hello,
Thanks for great and useful library!
I have one error when working with <mdl-radio>. I can't use [ngClass] for setting class 'is-checked'. Checked with another class - everything is working fine
Here is my code:
` <mdl-radio  name="address" [ngClass]="{'is-checked': address === selectedAddress}"
        (click)="selectedAddress = address" class="address-element" *ngFor="let address of addresses" 
        class="mdl-radio is-upgraded ng-untouched ng-valid is-checked ng-dirty">
        <input class="mdl-radio__button ng-untouched ng-pristine ng-valid" type="checkbox" name="address">
        <span>Travis Wilson</span>
        <ex-address [address]="address" format="flat"></ex-address>
        <button mdl-button mdl-colored="primary" *ngIf="allowEdit" (click)="editAddress(address)">Edit</button>
      </mdl-radio>`

**Comment by mseemann** [comment]
hi. please create a plnkr that demonstrates your problem. thx.

**Comment by Boichenko** [comment]
Sorry, did it in another way (like in you plunker demo), everything working fine.

**Comment by mseemann** [comment]
:+1:
