### ISSUE TITLE
Text icons

### ISSUE THREAD

**Issue by st-clair-clarke** [mseemann/angular2-mdl#448]
Hi,

In the bades I see the snippet:

`<mdl-icon mdl-badge="♥" mdl-badge-overlap>account_box</mdl-icon>`

Where can I find the icons package containing similar icons to "♥" or where is it coming from in your applciation

**Comment by mseemann** [comment]
there is no magic. this is just a unicode charcter - on windows for example Alt+3. same as here https://getmdl.io/components/index.html#badges-section.
