### ISSUE TITLE
Layout header does not re-render

### ISSUE THREAD

**Issue by grizzm0** [mseemann/angular2-mdl#452]
I've got a similar issue as I had with #89 but in the latest version.

I've got a full page login component. After you login I use `router.navigate(['/']);` to navigate to  a component for logged in users (contains the layout). This does not trigger the media query listeners from the looks of it.

The layout header has `margin-left: 240px;` and does not update even if I resize the page.

**Comment by nikoTM** [comment]
Could you please provide a plunkr ?

**Comment by mseemann** [comment]
pls provide a plnkr that demonstrates your problem. Thx.

**Comment by grizzm0** [comment]
I only managed to reproduce it on plnkr a few times. And only while in full preview mode.

http://embed.plnkr.co/f860usb4eBdTAsfDH5he/

**Comment by grizzm0** [comment]
Found out what's causing it and updated the plnkr.

The first login works fine. If you then click logout and try to login again the error appears.

**Comment by nikoTM** [comment]
I was not able to reproduce, what browser are you using ?

**Comment by grizzm0** [comment]
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36

**Comment by grizzm0** [comment]
@nikoTM Note that it only appears in mobile-view (drawer closed).

**Comment by nikoTM** [comment]
@mseemann seems like is-small-screen is not being added for some reason.

**Comment by mseemann** [comment]
@grizzm0 thx for finding this, @nikoTM thx for your help analysing this issue. the problem was that the MdlScreenSizeService did not provide the current screen size after a subscription. now it does - i hope:) will be available in a few minutes as 2.12.1.
