### ISSUE TITLE
Expose readonly on switch (or all toggles?)

### ISSUE THREAD

**Issue by tb** [mseemann/angular2-mdl#453]
Sometimes user needs to confirm change of value - in that case we need to disable changes on component with readonly and handle them with confirm callback.

**Comment by mseemann** [comment]
hi. can you submit a pr so we can see how it looks and feels?

**Comment by tb** [comment]
@mseemann I will do that

**Comment by mseemann** [comment]
@tb can we close this issue?

**Comment by tb** [comment]
Yes :)
