### ISSUE TITLE
Suggestion for mdl-textfield regarding error-message

### ISSUE THREAD

**Issue by maku** [mseemann/angular2-mdl#455]
I would like to control the error message handling for the textfield.

Would it be possible to pass in my own error handling component ?
e.g. via <mdl-textfield><my-own-error-handler></my-own-error-handler></mdl-textfield>

Regarding, the current code - The span which shows the errorMessage is always there. Would it be better to show the span only when an error is present (in terms of performance )

**Comment by mseemann** [comment]
Hi. Can you create a plunkr or even better a pr that demonstrates your intended usage? just to make clear I fully understand your request? Thx!

**Comment by mseemann** [comment]
Closed because of inactivity. Can be reopened if needed...
