### ISSUE TITLE
Chrome Autofill Not Showing on TextFields

### ISSUE THREAD

**Issue by pauljlucas** [mseemann/angular2-mdl#47]
Currently i am seeing that i cannot get chromes autofill to work on any of the text inputs from angular2-mdl. If you use standard MDL CSS you can normally double click a field with name and id (say username) and it will drop down a list of previously entered values.

I havent looked into the code enough to know why this would be happening, but have you noticed this as well? Has anyone seen similar issues on other browsers? 

Thanks!

**Comment by mseemann** [comment]
thx for your feedback. You right. Until now the name attribute isn't propagated to the html input element.  I'll fix this asap.

**Comment by pauljlucas** [comment]
@mseemann Thanks! Great repo by the way, saved me a lot of time and thankful that you are keeping it up to date with all of the Angular changes 👍

**Comment by mseemann** [comment]
fixed in npm version 1.4.4

**Comment by pauljlucas** [comment]
Tested and working on my end as well. Thanks!
