### ISSUE TITLE
Dialogs appear blurred in chrome

### ISSUE THREAD

**Issue by andrew-bents** [mseemann/angular2-mdl#472]
Mdl dialogs appear blurred in Chrome on Windows and Ubuntu.
I'll use the custom login dialog from the demo app to show the issue.
As I understand, it's because of position: fixed, z-index and translate properties on mdl-dialog-host-component. If you turn them off, the dialog becomes clear again:
[z-index is on](http://puu.sh/tEYhX/d5189dd900.png)
[z-index is off](http://puu.sh/tEYlk/b4d030bf81.png)

You can also tweak padding on the dialog host component to get rid of blur. Here I change padding from 1em to 0.9em (but if I set it to e.g. 0.8em the dialog will become blurred again):
[1em](http://puu.sh/tEYsl/dbf092f464.png)
[0.9em](http://puu.sh/tEYtn/644424006f.png)

**Comment by mseemann** [comment]
what is your chrome version. there are bugs in chrome, that make the text blurred. for example: https://bugs.chromium.org/p/chromium/issues/detail?id=521364

**Comment by andrew-bents** [comment]
It's 55.0.2883.87 m on Windows and 56.0.2924.76 m on Ubuntu

**Comment by mseemann** [comment]
still trying to reproduce this - without luck :( can anybody confirm this?

**Comment by andrew-bents** [comment]
Are you using Windows or Linux? Because as far as I know the issue is not present on macOS

**Comment by mseemann** [comment]
i have checked this on saucelab with windows 10 /chrome 55

**Comment by SamuelSchepp** [comment]
I can confirm this on Safari 10.0.3 on macOS Sierra 10.12.3. I was able to make the mdl-dialog sharp again by disabling the font-size attribute of .mdl-dialog in the dev-console in safari. http://imgur.com/a/NPhz6

**Comment by hccampos** [comment]
Blurry dialogs happen due to the CSS transform. It is not a bug, really. It happens because the dialog is an odd number of pixels high, causing it to be off by half a pixel.

**Comment by mseemann** [comment]
@hccampos thx for clarifying this!
