### ISSUE TITLE
this.dialog.close(); throwing error "this.dialog.close is not a function"

### ISSUE THREAD

**Issue by adriendomoison** [mseemann/angular2-mdl#478]
Hello,
I was wondering if it is a bug or if I am the only one to get this error, when I use the example of declarative dialog, everything works fine exept when I try to close the dialog programmatically after saving the change : 

```
    public saveUser() {
        this.userService.save(this.user);
        this.dialog.close();
    }
```

I get the error `this.dialog.close is not a function`

I am really surprised because when I use it in the HTML it works fine : 

`<button mdl-button (click)="dialog.close()" mdl-ripple>Cancel</button>`

So is it just me forgetting something ?

**Comment by mseemann** [comment]
hi, please create a plnkr that demonstrates your problem. thanks.

**Comment by adriendomoison** [comment]
I figured it out, an other element had the same name in my DOM, that's where the bug was coming from :)
The console errors are as good as AngularJS :/
So it was on my side ! Thanks !

**Comment by mseemann** [comment]
no prob:)
