### ISSUE TITLE
Weird behavior on Mdl-Textfield type Number

### ISSUE THREAD

**Issue by nikoTM** [mseemann/angular2-mdl#495]
Number textfield not working as expected.

1. It ignores the first input of minus (`-`) when trying to write a negative number on the first input.
2.  Try writing `e1`, moving the cursor in the front of input and writing another `1`. It converts into a 10 (this is understandable, but not the default behavior of number input).
3. Try writing `1e`, the input is being removed.

http://plnkr.co/edit/prgz1DipVSFeixiPNOyE?p=preview

**Comment by mseemann** [comment]
the reason: https://github.com/mseemann/angular2-mdl/issues/275 e.g. what you see is what parseFloat is doing with your input value.

**Comment by nikoTM** [comment]
@mseemann who do I blame now ? :D

**Comment by mseemann** [comment]
@nikoTM I don't know :D  and I have no idea how to change this. For sure the parsing can be made more smarter. But I'm affraid this will be a nightmare until it works in all cases...
