### ISSUE TITLE
Tooltips don't calculate correctly when placed in overflowing containers.

### ISSUE THREAD

**Issue by travislaynewilson** [mseemann/angular2-mdl#501]
I placed an element with `[mdl-tooltip]` into an element found in a container with `overflow: auto` and  fixed measurements. When the tooltip displays, it is moved and recalculated based on the scroll-position of the overflowing container rather than the position of the element it is mapped to. This causes the tooltip to appear away from it's paired element when the container is scrolled.

**Comment by mseemann** [comment]
hi. please create a plnkr that demonstrates your issue. thx.

**Comment by travislaynewilson** [comment]
It'll take me some time to figure out how to use Angular 2 with Plunker, so I'll find another solution for now. I'll try to get you a code sample very soon.

**Comment by mseemann** [comment]
you can use this template http://plnkr.co/edit/I3dLfLUDIH2xlEJqj0da?p=preview

**Comment by mseemann** [comment]
any update on this?

**Comment by mseemann** [comment]
can be reopened if needed...

**Comment by mastanik** [comment]
Hey, not sure if it is the same problem, but check out this example http://plnkr.co/edit/dhmbLG?p=preview
