### ISSUE TITLE
mdl-textfield and input attributes / events

### ISSUE THREAD

**Issue by grizzm0** [mseemann/angular2-mdl#51]
mdl-textfield does not support the autofocus attribute.

It also doesn't look like the focus/blur events are available to catch.
Eg. 
```html
<mdl-textfield (blur)="doStuff()">

**Comment by mseemann** [comment]
you are right. this needs to be done...

**Comment by mseemann** [comment]
will be part of the next release. i think this will be tomorrow :)

**Comment by mseemann** [comment]
done in npm version 1.4.6
