### ISSUE TITLE
Does mdl-textfield have any support for typeahead or datalist?

### ISSUE THREAD

**Issue by dksheffield** [mseemann/angular2-mdl#525]
Trying to use Angular2 + angular2-mdl for a project and i'm needing typeahead or at least datalist support for mdl-textfield. Is there an example out there where this works? Thanks

**Comment by mseemann** [comment]
you can checkout @angular2-mdl-ext/select (https://github.com/mseemann/angular2-mdl-ext/tree/master/src/components/select). this package did not provide support for typeahead or  a datalist because mdl did not support it.
