### ISSUE TITLE
Disabling a button while the tooltip is up persists the tooltip.

### ISSUE THREAD

**Issue by amdefran** [mseemann/angular2-mdl#535]
When I disabled a button and the mdl-tooltip was present, there was no way to remove the tooltip.  Basically, I had a list and when the user hits the button to jump to the first set of data, I disabled the button since they were already at the first set. The tooltip stays around until the button is re-enabled.

**Comment by mseemann** [comment]
please create a plnkr that demonstartes your problem. thx.

**Comment by amdefran** [comment]
http://plnkr.co/edit/1narogFKKGYD9JlWsny3

If you click on top button, you will see the tooltip stay around.  It doesn't go away until you hit the second button.

**Comment by mseemann** [comment]
pointer events are not fired on disabled elements. (have a look for a discussion on that topic: http://stackoverflow.com/questions/3100319/event-on-a-disabled-input)

you can change your code in this way to make possible what you are trying to do:

```
       <span mdl-tooltip="blah">
          <button mdl-button  mdl-button-type="fab" mdl-colored="primary" 
            [disabled]="itemDisabled" (click)="itemDisabled=!itemDisabled">
            <mdl-icon>add</mdl-icon>
          </button>
       </span>
```
