### ISSUE TITLE
mdl-layout: mdlscreensizeservice fires wrong values -> breaks layout

### ISSUE THREAD

**Issue by mscu** [mseemann/angular2-mdl#536]
Hi Michael,

unfortunately i found some weird behavior using a custom screensize.

1. the values are fired to late when you resize the screen

![adc95857ac](https://cloud.githubusercontent.com/assets/545229/22839267/ff7d0c58-efc8-11e6-82ab-69734028ff13.gif)

2. if you change the orientation (i.e. ipad) two values are fired, the second one is unfortunately the wrong one

![3e22cb281f](https://cloud.githubusercontent.com/assets/545229/22839308/238247b2-efc9-11e6-8d33-428d5f87c9ab.gif)

I have created a small demo app to reproduce it:

https://github.com/matthiasscudlik/mdl-layout-bug

What is kind of weird is that in my real app i also encounter the issue that at some point (i.e. screen orientation change) the header still has the side offset of the drawer, but the drawer is not visible, so the header starts with with the "offset" and the side is white/empty.

Thanks for this great library and best regards,
Matthias

**Comment by mseemann** [comment]
hi. if you use this feature please make sure that you not use any prebuilt css from getmdl.io (e.g. https://code.getmdl.io/1.1.3/material.indigo-pink.min.css) and only use the included scss with the $layout-screen-size-threshold variable. Can you change your example? After that i'll have a look again. thx.

**Comment by matthiasscudlik** [comment]
Hi Michael,

i removed all the css and added  a console.log for layoutScreenSizeThreshold, which is unfortunately still 1024 in this case, but i don't know why.

Thanks and best regards,
Matthias

**Comment by mseemann** [comment]
you have created a new token: `const LAYOUT_SCREEN_SIZE_THRESHOLD = new OpaqueToken('layoutScreenSizeThreshold');`. you need to import the existing token from the lib to get this working:

```
import { LAYOUT_SCREEN_SIZE_THRESHOLD } from 'angular2-mdl';
```

**Comment by matthiasscudlik** [comment]
you're right, sorry for my mistake and thanks a lot for helping me out.

**Comment by mseemann** [comment]
no problem!

**Comment by mscu** [comment]
Hi Michael,

unfortunately i have a similar issue again after upgrading to ng4 and mdl4.
This time it does not seem to be related to the service but the compination of fixed header and drawer.

The header size does not get larger once the layout changes to the compact mode so there is a gap on the left side.

When i remove the custom layout threshhold its the other way around: the header does not get smaller in the non compact layout so that content on the left side of the header is hidden.

I have created a demo app: https://github.com/mscu/ng4-mdl

The same code works with ng2 and mdl2.

Any help is highly appreciated :)

Thanks and best regards,
Matthias

**Comment by mscu** [comment]
@mseemann can you please check this?

Thanks a lot! :)

**Comment by mseemann** [comment]
Hi. Sorry forget to look into this. I'm on vacation right now. Reopen this to have a reminder if I am back....

**Comment by mscu** [comment]
Thanks a lot, enjoy your vacation :)

**Comment by mseemann** [comment]
this seems to be a problem with zone js not with angular. a fix is on the way. and sorry for the really late response:(

**Comment by mscu** [comment]
works fine, thanks a lot :)
