### ISSUE TITLE
Snackbar not being centered properly

### ISSUE THREAD

**Issue by nikoTM** [mseemann/angular2-mdl#537]
When the drawer is in view (>= 1024px) snackbar gets off-center. Here's the plunkr to reproduce: http://embed.plnkr.co/n9Pxi1yRhiRYdhEJRx7a/

Just resize the window to have the drawer in view and click the button.  I think maybe this [line](https://github.com/google/material-design-lite/blame/mdl-1.x/src/snackbar/_snackbar.scss#L52) should have been *max-width* instead of *min-width* ? I might be missing something, feel free to tag this as a question.

**Comment by mseemann** [comment]
this seems to be by design of getmdl.io. i can't change it. you can try to discuss this at their project.

**Comment by nikoTM** [comment]
I see, thanks.
