### ISSUE TITLE
Add sidenav or how to add second layout on right

### ISSUE THREAD

**Issue by istiti** [mseemann/angular2-mdl#54]
very nice project, I think really choose it to my next project.

It will be fine to add 
- sidenav feature (like https://material.angularjs.org/latest/demo/sidenav) 
- tree view or folder view 
- dialog

I think if you add milestone...what will be furthur developement, what do you plan to add and when?  what's in your shortlist ... maybe something like this will avoid issue like mine.

**Comment by mseemann** [comment]
Hi, thx for your feedback. 

- side nav feature: this package will only provide components that are part of material design lite (getmdl.io). MDL only has a drawer in layouts. pls have look: https://getmdl.io/components/index.html#layout-section. This package has this feature too: http://mseemann.io/angular2-mdl/layout. 

- tree view: same as before. if i would add additional features i would break the possibility to use the original css from MDL and i don't can provide the manpower to make all the css by myself. Nevertheless MDL 2.0 is on it's way. If they provide a treeview I'll also add this feature.

- dialog: will come. as you have seen :-) I don't know when. MDL is using a polyfill so they only provide the css for this component. I'm still looking around to find a clean angular2 way to provide such a dialog. But this package is open to pullrequests!

**Comment by istiti** [comment]
I wonder if you use something which css class which do this effect on your mdl-layout so:

I try to use material2 and angular2-mdl together but there is problem when I try this on my root component:

```
//1.this is material2 sidenav layout which wrap angular2-mdl layout
<md-sidenav-layout>
  <md-sidenav align="end" mode="over" >
    <h1>hello</h1>
  </md-sidenav>

  // 2.this is angular2-mdl layout
  <mdl-layout>
    <mdl-layout-header>...</mdl-layout-header>
    <mdl-layout-drawer>...</mdl-layout-drawer>
    <mdl-layout-content>
      <router-outlet></router-outlet>
    </mdl-layout-content>
  </mdl-layout>

</md-sidenav-layout>
```

This code hide my all content... my page is blank !


BUT When I wrap only router-outler it works... Your layout is displayed with this 

  ```
<mdl-layout>
    <mdl-layout-header>...</mdl-layout-header>
    <mdl-layout-drawer>...</mdl-layout-drawer>
    <mdl-layout-content>
      <md-sidenav-layout>
        <md-sidenav align="end" mode="over" >
          <h1>hello</h1>
       </md-sidenav>
         <router-outlet></router-outlet>
       </mdl-layout-content>
    </md-sidenav-layout>
  </mdl-layout>

```
