### ISSUE TITLE
Packaging the module for RC6 seems to not be working

### ISSUE THREAD

**Issue by pauljlucas** [mseemann/angular2-mdl#55]
Hey mseemann, 

Sorry to keep throwing these on you. I upgraded angular CLI to webpack.8 version and also upgraded angular to RC6 and when i import MDLModule i get this error:

Unexpected value 'MdlModule' imported by the module 'AppModule'

it may be something to do around this: https://github.com/angular/angular-cli/issues/1831

but im not quite sure. Ill try to help take a look through your module setup and see if i see any issues.

**Comment by mseemann** [comment]
Hey pauljlucas,

need to check this. It will need some time. I would appreciate any help!

**Comment by pauljlucas** [comment]
More error details:
Coming from metadata_resolver.js:230
            if (meta.imports) {
                flattenArray(meta.imports).forEach(function (importedType) {
                    var importedModuleType;
                    if (isValidType(importedType)) {
                        importedModuleType = importedType;
                    }
                    else if (importedType && importedType.ngModule) {
                        var moduleWithProviders = importedType;
                        importedModuleType = moduleWithProviders.ngModule;
                        if (moduleWithProviders.providers) {
                            providers_1.push.apply(providers_1, _this.getProvidersMetadata(moduleWithProviders.providers, entryComponents_1, "provider for the NgModule '" + stringify(importedModuleType) + "'"));
                        }
                    }
                    if (importedModuleType) {
                        var importedMeta = _this.getNgModuleMetadata(importedModuleType, false);
                        if (importedMeta === null) {
                            throw new Error("Unexpected " + _this._getTypeDescriptor(importedType) + " '" + stringify(importedType) + "' imported by the module '" + stringify(moduleType) + "'");
                        }
                        importedModules_1.push(importedMeta);
                    }
                    else {
                        throw new Error("Unexpected value '" + stringify(importedType) + "' imported by the module '" + stringify(moduleType) + "'");
                    }
                });
            }

**Comment by pauljlucas** [comment]
I went through importing all of the sub modules individually and received the same errors for each module:

Uncaught Error: Unexpected value 'MdlButtonModule' imported by the module 'AppModule' Unexpected value 'MdlLayoutModule' imported by the module 'AppModule'

for all:
  MdlButtonModule,
  MdlLayoutModule,
  MdlChekboxModule,
  MdlChipModule,
  MdlSpinnerModule,
  MdlRippleModule,
  MdlBadgeModule,
  MdlShadowModule,
  MdlCardModule,
  MdlRadioModule,
  MdlProgressModule,
  MdlIconModule,
  MdlIconToggleModule,
  MdlListModule,
  MdlSliderModule,
  MdlSwitchModule,
  MdlTooltipModule,
  MdlTableModule,
  MdlMenuModule,
  MdlTabsModule,
  MdlTextFieldModule


Will keep updating the thread as i go with more info unless you want to move to stackexchange (I saw your readme update) or some chat

**Comment by mseemann** [comment]
just take a look at rc6 - it seems i must have missed some deprecation warnings. got a lot of compilation errors. stay tuned...

**Comment by mseemann** [comment]
just a status note: i have "only" two main issues:

- the angular router throws during initialization
- the tests are not running because of changes in the karma configuration

if i remove the router for the e2e app all works now. If you are  interested i can commit my current work to the master...

**Comment by pauljlucas** [comment]
Nah dont bring down your website. I know people are probably not updated yet so it isnt a big deal. For the router, when i went from RC4-RC5 i had some issues because you need to do a couple different things with the router. First make sure you are on: and second make sure to setup your router like this:

```
const appRoutes: Routes = [
  { path: '', component: HomeComponent },
];

export const appRoutingProviders: any[] = [

];

export const routing = RouterModule.forRoot(appRoutes);


```

I do have my routes in a separate file: app.routing.ts as well just to clean it up and standardize it :)

**Comment by mseemann** [comment]
Thx, for your feedback! I'll check the and adopt the router config....

**Comment by mseemann** [comment]
https://github.com/angular/angular/issues/11277

**Comment by mseemann** [comment]
status: routing problems solved. still fighting with the test configuration...

**Comment by mseemann** [comment]
i have released npm version 1.5.0 which should be run under rc6. Looking forward to hear from you:)

**Comment by pauljlucas** [comment]
Will give this a test tomorrow and confirm things are working! On holiday right now so I can't jump on it this second. Thanks mseemann

**Comment by pauljlucas** [comment]
Just tested. Seems to be working perfectly! Also saw the radio buttons working now as well. Thanks Mseemann.

**Comment by mseemann** [comment]
Pleased  to hear that :+1:
