### ISSUE TITLE
Textfield: floating label font size for invalid state

### ISSUE THREAD

**Issue by adasq** [mseemann/angular2-mdl#556]
By default, floating-label font size for invalid and empty textfield is set to `$input-text-floating-label-fontsize` which is `12px`. So, the font size for empty text-field does not change (no matter if it is focused or not) which is tricky I think.
It's because the line: https://github.com/mseemann/angular2-mdl/blob/v2.13.1/src/lib/scss/mdl/textfield/_textfield.scss#L157
I think the line should be removed, so then, by default, floating-label will change to `$input-text-font-size` for not focused and empty fields, and for `$input-text-floating-label-fontsize` for focused - just like the valid field behaviour.

Then, user still can change it to fixed value, by overriding `is-invalid` class font size.

**Comment by mseemann** [comment]
hi. We can't change this because this is the repackaged code from getmdl.io. If it is changed there, it would be available here too.
