### ISSUE TITLE
Is it possible to show icon (or img) in table rows?

### ISSUE THREAD

**Issue by ikocev** [mseemann/angular2-mdl#569]
Hi,
I couldn't find anything in the documentation to insert an icon in the table rows. I also looked into the code and I think this is not possible right now?!? Are you planing to add this feature? Or maybe there is some other workaround that I couldn't saw...

**Comment by mseemann** [comment]
hi. this is not planned. because it is really easy to use the css classes from getmdl.io to create any table you want. the table in this lib is only responsible to show a small amount of simple data.
