### ISSUE TITLE
one content in tabs

### ISSUE THREAD

**Issue by istiti** [mseemann/angular2-mdl#58]
hi

quick question: I wonder I it's possible have on content for my tabs, because I need a <router-outlet> and I can't do something like : 

`
<mdl-layout-tab-panel>
        <mdl-tab-panel-title>
          <mdl-icon class="mdl-cell--hide-phone">gavel</mdl-icon><span>Contrat</span>
        </mdl-tab-panel-title>
        <mdl-tab-panel-content>
          **<router-outlet></router-outlet>**
        </mdl-tab-panel-content>
      </mdl-layout-tab-panel>

      <mdl-layout-tab-panel>
        <mdl-tab-panel-title>
          <mdl-icon class="mdl-cell--hide-phone">forum</mdl-icon><span>Correspondance</span>
        </mdl-tab-panel-title>
        <mdl-tab-panel-content>
          **<router-outlet></router-outlet>**
        </mdl-tab-panel-content>
      </mdl-layout-tab-panel>

      <mdl-layout-tab-panel>
        <mdl-tab-panel-title>
          <mdl-icon class="mdl-cell--hide-phone">receipt</mdl-icon><span>Offre</span>
        </mdl-tab-panel-title>
        <mdl-tab-panel-content>
          **<router-outlet></router-outlet>**
        </mdl-tab-panel-content>
      </mdl-layout-tab-panel>

      <mdl-layout-tab-panel>
        <mdl-tab-panel-title>
          <mdl-icon class="mdl-cell--hide-phone">business_center</mdl-icon><span>Projet</span>
        </mdl-tab-panel-title>
        <mdl-tab-panel-content>
          **<router-outlet></router-outlet>**
        </mdl-tab-panel-content>
      </mdl-layout-tab-panel>
      <mdl-layout-tab-panel>
        <mdl-tab-panel-title>
          <mdl-icon class="mdl-cell--hide-phone">shopping_cart</mdl-icon><span>Commande</span>
        </mdl-tab-panel-title>
        <mdl-tab-panel-content>
          **<router-outlet></router-outlet>**
        </mdl-tab-panel-content>
      </mdl-layout-tab-panel>

      <mdl-layout-tab-panel>
        <mdl-tab-panel-title>
          <mdl-icon class="mdl-cell--hide-phone">free_breakfast</mdl-icon><span>Divers</span>
        </mdl-tab-panel-title>
        <mdl-tab-panel-content>
          **<router-outlet></router-outlet>**
        </mdl-tab-panel-content>
      </mdl-layout-tab-panel>
`

do you have better integration for this ? what do you  advice me...

**Comment by mseemann** [comment]
Yes it is. Please check out the examples at the demos. There is a tab with text and icon. 

It would be great if you would use stackoverflow for quesstions. Because I'm short of time. Thank you very much!
