### ISSUE TITLE
mdl-textfield and external directives

### ISSUE THREAD

**Issue by stepanzarubin** [mseemann/angular2-mdl#582]
I am trying to use [text-mask](https://github.com/text-mask/text-mask/tree/master/angular2#readme)

The code below
```
<mdl-textfield type="text" label="Phone" [textMask]="{mask: phoneMask}" [(ngModel)]="phone" floating-label></mdl-textfield>
```

Throws an error:
`More than one custom value accessor matches form control with unspecified name attribute`

**Comment by mseemann** [comment]
please create a plnkr. thx.

**Comment by mseemann** [comment]
closing this because of missing input. can be reopened if needed...

**Comment by stepanzarubin** [comment]
Is this correct plnkr template? [http://embed.plnkr.co/f860usb4eBdTAsfDH5he/](url)
I have not found a way to create a fresh example.
