### ISSUE TITLE
table not works

### ISSUE THREAD

**Issue by istiti** [mseemann/angular2-mdl#61]
I'my trying to implement table but it seems not working.. I do not have type ITableItem, I tried ITableModelItem as my screen, and my error I don't understand it

![table error](https://cloud.githubusercontent.com/assets/2789203/18249702/3396703a-7380-11e6-917c-9759905c5b84.JPG)

**Comment by mseemann** [comment]
you need to provide a table model. how to do that can be found here: https://github.com/mseemann/angular2-mdl/blob/master/src/app/tables/table.component.ts.

again: please use stackoverflow for questions! thanks.

**Comment by istiti** [comment]
yes I can use stackoverfloew but I think always it's issue, like here on my screenshot line 26 is not tableModel ? but ok please appologize
