### ISSUE TITLE
Button not working in mdl-list while list with mdl-ripple

### ISSUE THREAD

**Issue by livelazily** [mseemann/angular2-mdl#618]
If `mdl-list-item` combine with `mdl-ripple`, and an button in it's `mdl-list-item-secondary-action`, then the button can not be click

Example is here:
http://plnkr.co/edit/dnQXqG?p=preview

**Comment by mseemann** [comment]
yes you are right. You may have a valid usecase for a mdl-list-item with a ripple effect. but this feature was an experiment of mine. getmdl.io dosn't supprt it. You may also checkout this feature on a mobile device - you'll see why I not recommend using it. In the next release (version 3.0) I'm going to remove the mdl-ripple direktive from the mdl-list-item.
