### ISSUE TITLE
BrowserModule imported twice with angular 4.rc2

### ISSUE THREAD

**Issue by guzmo** [mseemann/angular2-mdl#639]
Hey!

I've had some problems with BrowserModule being loaded twice in Angular 4.rc2 with Lazy Loading.
After alot of debugging I've figured out the problem is gone when I remove everything that has to do with MdlModule ( the new @angular-mdl ) and I think it has something to do with BrowserAnimationModule, not sure though.

I'm using MdlModule in a SharedModule so maybe I'm doing something wrong but an answer would be really appreciated :) been on it for like 2 days now.

Cheers!

**Comment by guzmo** [comment]
Oh, btw! I'm using "@angular-mdl/core": "^3.0.0-beta.1"

**Comment by guzmo** [comment]
Installed beta.4 via git+https.... but it didn't help :/

**Comment by guzmo** [comment]
I think it breaks because you are importing import { BrowserAnimationsModule } from '@angular/platform-browser/animations'; in src/lib/components/dialog/index.ts. 

I commented out that row and now it works like a charm. BrowerAnimationsModule imports BrowserModule I guess.

**Comment by guzmo** [comment]
Ye, I removed that line and now everything is working, I think you should not import BrowserAnimationModule but instead tell the user of the library to import it, maybe? I'm guessing here :)

**Comment by hccampos** [comment]
Getting the same problem here. Indeed the problem is with the `BrowserAnimationModule` which causes the Browser module to be included multiple times.

**Comment by mseemann** [comment]
@hccampos as you can see in the broken build it's not that easy. need some time to find a solutions. the main problem is that they have removed the animation function of the renderer in angular 4 :( 

@guzmo 3.0.0-beta.4 is the latest but i have only set the beta tag and not the latest tag in npm... trying to fix this asap.

**Comment by hccampos** [comment]
@mseemann indeed. I should have added the module in the test.

**Comment by mseemann** [comment]
@hccampos and i need to test that it really works without importing any animation module... the broken test is a hint that there could be a problem...

**Comment by hccampos** [comment]
@mseemann indeed, it seems to be more complicated. I managed to get some of the tests passing, but still not the textfield ones. Apparently, if you import the BrowserModule in a test, other tests get affected by it and event handlers stop working somehow.

**Comment by hccampos** [comment]
Managed to get most tests passing, except for the ones related to focus in `mdl-textfield.component.spec.ts`. They pass if the Chrome window has focus, and fail otherwise. Others running into similar problems: http://stackoverflow.com/questions/41992155/angular-2-jasmine-browser-focus-when-testing-focus

**Comment by mseemann** [comment]
published as @angular-mdl/core@3.0.0-beta.5

thx for your help guys!

**Comment by hccampos** [comment]
As mentioned in the commit... Thank you!

**Comment by guzmo** [comment]
Thank you too for a quick fix, both of u :)
