### ISSUE TITLE
mdl-Layout: scroll to link not working anymore

### ISSUE THREAD

**Issue by UndefeatedChampion** [mseemann/angular2-mdl#642]
First off, I really like this library. I appreciate the different layout modes.
Unfortunately, I can't trigger programmatic scroll to top anymore. Neither jQuery or native Angular solutions worked for me.
Do you know a way to fix this behavior?
Thanks in advance.

**Comment by mseemann** [comment]
Hi. Please provide a plknr that demonstrates your problem. Thx.

**Comment by mseemann** [comment]
no more input provided. closing this. can be reopened if needed.
