### ISSUE TITLE
mdl-textfield label

### ISSUE THREAD

**Issue by stepanzarubin** [mseemann/angular2-mdl#654]
When I do not set label for the textfield (placeholder is enough), it still generates html for it:

```
<mdl-textfield type="text" placeholder="First Name" [(ngModel)]="first_name"></mdl-textfield>
```
still generates:
```
<label class="mdl-textfield__label" for="mdl-textfield-0"></label>
```

I think this empty label tag should not be there because it affects on styles and does not make sense.
To fix it I have to use style:

```
mdl-textfield label {
     display: none;
}
```

**Comment by mseemann** [comment]
hi. please create a plnkr. thx.

**Comment by stepanzarubin** [comment]
I am not comfortable with plnkr, is my explanation not clear?

**Comment by mseemann** [comment]
here is a template: http://plnkr.co/edit/I3dLfLUDIH2xlEJqj0da?p=preview

i want to make sure i understand correctly what your problem is. also i have done a quick look and i can't see any difference in the ui with or without a label.

**Comment by stepanzarubin** [comment]
Here you go [http://plnkr.co/edit/Z8AafJ0iegc9mIkyiyIo?p=preview](http://plnkr.co/edit/Z8AafJ0iegc9mIkyiyIo?p=preview)

There are 2 inputs, one with a placeholder, another one with a label. The one with a label generates label tag which is correct, but when there is no label it still generates empty label tag.

I think there will be no difference in ui until we add some custom styles.

**Comment by mseemann** [comment]
ok, but why did you set the label to display: none? I can't see any difference in the ui.

**Comment by stepanzarubin** [comment]
I think some custom styles were causing a display issue for this empty label tag or an attempt to apply a mask, sorry, maybe I should not open this. We have fixed it it with `display: none` because nothing else worked for us.

**Comment by mseemann** [comment]
No! It's ok. I'm just trying to understand what are the consequences if I would remove the label tag. That is the easy part. The problem is: would it be a potentially breaking change for others who rely on this tag.

**Comment by stepanzarubin** [comment]
Yeah, I understand. The only use case for an empty tag I can think about is updating its contents dynamically, but there can be other, as well as potential issue for styling.

I am closing this. Thanks for your feedback.
