### ISSUE TITLE
Problem with mdl-tabs component.

### ISSUE THREAD

**Issue by valiknet18** [mseemann/angular2-mdl#686]
Hello, i have a some problem with mdl-tabs component. Tab change state, only after two clicks to specific tab element.
Who had the same problem?

**Comment by hccampos** [comment]
Are you using the `OnPush` change detection strategy? We've had several problems with the tabs when using it.

**Comment by valiknet18** [comment]
I'm not using ```OnPush``` in component with tabs. But i'm using this change detection strategy in some another components.
I had tried remove it from another components, but it doesn't helped me.

**Comment by mseemann** [comment]
hi. please provide a plnkr that reproduces your problem (template: http://plnkr.co/edit/I3dLfLUDIH2xlEJqj0da?p=preview). thx.

**Comment by valiknet18** [comment]
I'm sorry. I removed ```OnPush``` in main module, and it's helped me.
Strange, but it didn't helped me early.
