### ISSUE TITLE
Only enable tooltip when tooltip text is longer than 50 characters

### ISSUE THREAD

**Issue by thaihacong** [mseemann/angular2-mdl#687]
Can I enable mdl-tooltip only when the tooltip text is longer than 50 characters?
Or, is there anyway to set condition for mdl-tooltip?

Currently, I am using mdl-tooltip inside a mdl-textfield. And I just want to only display tooltip if the input text is longer than a specific length.

`<mdl-textfield type="text" [(ngModel)]="description" [tooltip]="description"></mdl-textfield>`

**Comment by mseemann** [comment]
this is not supported out of the box. but it should be possible to change the dscription ...
