### ISSUE TITLE
mdl-tooltip is not updated when its value changes

### ISSUE THREAD

**Issue by thaihacong** [mseemann/angular2-mdl#688]
In this mdl-textfield, 
`<mdl-textfield type="text" [(ngModel)]="description" [tooltip]="description">`
mdl-tooltip is not updated when `description` changes.

**Comment by mseemann** [comment]
hi. please create a plknr that reproduces your problem. thx.

**Comment by thaihacong** [comment]
Hi @mseemann, here is my plunker. http://plnkr.co/edit/RiGGDF?p=preview

Here is the empty tooltip after the application is loaded.

![mdl-tooltip-1](https://cloud.githubusercontent.com/assets/8019304/24104083/91611792-0d81-11e7-9c68-c7f304e707c2.png)

It does not change when I type 'Sample description' in the textfield.

![mdl-tooltip-2](https://cloud.githubusercontent.com/assets/8019304/24104090/961ae786-0d81-11e7-981a-211477ccbb2c.png)

**Comment by thaihacong** [comment]
As a work around at the moment, anyone who wants to have this feature can do like below
`<mdl-textfield type="text" [(ngModel)]="description" [title]="!!description ? description : ''"></mdl-textfield>
`
The title is also hidden if it is empty or undefined.
