### ISSUE TITLE
Creating two custom dialog in two different components causes issue

### ISSUE THREAD

**Issue by vsharma2266** [mseemann/angular2-mdl#712]
I have two implementations of custom dialogs in two different components in two different routes.
One implementation is in one feature module as shown:
```
showDialog() {
    let pDialog = this.dialogService.showCustomDialog({
      component: DashboardWarningComponent,
      providers: [{provide: incompleteFields, useValue: this.noteValue}],
      isModal: true,
      styles: { 'padding': '0' },
      clickOutsideToClose: false,
      enterTransitionDuration: 0,
      leaveTransitionDuration: 0
    });
  }
```

Another implementation is as follows:

```
  showDialog() {
    let pDialog = this.dialogService.showCustomDialog({
      component: ModalAccountTransactionComponent,
      providers: [{provide: ACCOUNT_ID, useValue: this.accountId}],
      isModal: true,
      styles: {'width': '396px', 'padding': '24px'},
      clickOutsideToClose: false,
      enterTransitionDuration: 400,
      leaveTransitionDuration: 400
    });
  }
```

They both are in different routes.
On application starts, if i am at routes 1 where my 1st Dialog is implemented, the Dialog works properly.
When i navigate to another route which does not have any custom Dialog, and come back to route 1, the Dialog still works well.
When i navigate from route 1 to route 2, where my second implementation of Custom dialog exists, and then open my Dialog, it fails to open. 

Please advice.

**Comment by mseemann** [comment]
Hi. Please create a plnkr that demonstrates your problem. If not possible please create a github project with minimal functionality so i can check the problem. Thx.

**Comment by mseemann** [comment]
no input since 9 days. can be reopened if needed.
