### ISSUE TITLE
Dialog is not closing in IE and Firefox

### ISSUE THREAD

**Issue by david-lehmann** [mseemann/angular2-mdl#724]
Since my last update to the latest Version of your library and of Angular 4 final the Dialog (declarative) isn't closing anymore in IE 10 and Firefox. It still works fine in Chrome.
After clicking to the close button the background is no longer greyed out (disabled) but the dialog remains visible!
This Issue can be reproduced with your own CLI-Demoproject "https://github.com/mseemann/angular-mdl-a4-angular-cli." (as soon as you get it up and running because of the Version-Conflicts with zone.js it currently has ;-) ).

**Comment by SamuelSchepp** [comment]
i can confirm this.

**Comment by benschs** [comment]
I have the same issue.
