### ISSUE TITLE
mdl-checkbox [attr.checked]

### ISSUE THREAD

**Issue by stepanzarubin** [mseemann/angular2-mdl#792]
I need to check mdl-checkbox conditionally.

For default checkboxes something like this will work:

```
[attr.checked]="value ? '' : null"
```

See plkr [http://plnkr.co/edit/eJlMXEq1flSdj0qyZ3HT?p=preview](http://plnkr.co/edit/eJlMXEq1flSdj0qyZ3HT?p=preview)

**Comment by stepanzarubin** [comment]
Sorry, I think it should work with ngModel.

**Comment by mseemann** [comment]
👍
