### ISSUE TITLE
Unexpected value 'MdlModule' imported by the module 'AppModule' -- back again on RC.7

### ISSUE THREAD

**Issue by YeomansIII** [mseemann/angular2-mdl#80]
I'm getting this error when when trying to run my app on @angular rc.7.

It didn't seem like there were really any breaking changes in rc.6 -> rc.7 so perhaps I'm doing something wrong?  I'm running angular2-mdl 1.5.2.

Here is the full stack trace:
```
zone.js:129 Uncaught Error: Unexpected value 'MdlModule' imported by the module 'AppModule'(anonymous function) @ 
metadata_resolver.js:245CompileMetadataResolver.getNgModuleMetadata @ 
metadata_resolver.js:230RuntimeCompiler._compileComponents @ 
runtime_compiler.js:142RuntimeCompiler._compileModuleAndComponents @ 
runtime_compiler.js:80RuntimeCompiler.compileModuleAsync @ 
runtime_compiler.js:71PlatformRef_._bootstrapModuleWithZone @ 
application_ref.js:328PlatformRef_.bootstrapModule @
application_ref.js:310main @ 
main.browser.ts:8ZoneDelegate.invokeTask @
zone.js:225Zone.runTask @
zone.js:125ZoneTask.invoke @
zone.js:293
```

**Comment by mseemann** [comment]
unfortunately there are some breaking changes. the package is updated to rc7 (npm version 1.6.0) please try out this one...

**Comment by mseemann** [comment]
@YeomansIII did upgrading the package to 1.6 solved this problem? have you already upgraded to angular2 final?

**Comment by YeomansIII** [comment]
@mseemann I didn't get a chance to test the new version.  I upgraded to angular 2 final and decided to stick with the official @angular/material2 package for now as they are now including the components that I was using this library for.  However, thank you very much for the quick response.
