### ISSUE TITLE
Make MdlTextFieldComponent::setFocus() public

### ISSUE THREAD

**Issue by grizzm0** [mseemann/angular2-mdl#81]
I've got an input that always needs to keep focus.

I'm switching over to angular2-mdl from angular2-material as it's lacking a lot of features. I had something similar working in angular2-material already and tried the following when switching to angular2-mdl. But setFocus() is protected which breaks the whole thing.

```html
<mdl-textfield #input [autofocus]="true" (blur)="focus()" ...></mdl-textfield>
```

```ts
export class InputScanner implements OnInit {
  @ViewChild('input') input:MdlTextFieldComponent;

  protected focus():void {
    this.input.setFocus();
  }
}
```

**Edit:**
Don't forget to create an if-statement to make sure this.inputEl is set. ;)

**Comment by mseemann** [comment]
will be part of the next release.

**Comment by grizzm0** [comment]
@mseemann As my edit stated you might want to make sure this.inputEl is actually set. Ran into an error there myself while playing around.

**Comment by mseemann** [comment]
see 81bc83b365ec8a86a321dab39196211565914d77

**Comment by mseemann** [comment]
npm version 1.7.0
