### ISSUE TITLE
"You did not provide a ViewContainerRef. " exception due calling selectDate

### ISSUE THREAD

**Issue by suchwerk** [mseemann/angular2-mdl#826]
A "You did not provide a ViewContainerRef. " exception is thrown when calling selectDate.

```javascript

    "@angular-mdl/core": "^4.0.3",
    "@angular-mdl/datepicker": "0.0.2",
    "@angular-mdl/popover": "^0.6.3",
    "@angular-mdl/select": "^0.10.4",

 <button mdl-button (click)="pickADate($event)" mdl-button-type="icon" mdl-ripple>
    <mdl-icon>event</mdl-icon>
 </button>
 <span>{{ selectedDate?.format('LL') }}</span>

import { MdlDatePickerService } from '@angular-mdl/datepicker';
import * as moment from 'moment';

 constructor(
    private datePicker: MdlDatePickerService) { }

  public pickADate($event: MouseEvent) {
    this.datePicker.selectDate(this.selectedDate, { openFrom: $event }).subscribe((selectedDate: Date) => {
      this.selectedDate = selectedDate ? moment(selectedDate) : null;
    });
  }
```

**Comment by mseemann** [comment]
Please read the exception carefully. The answer is in the exception message!

**Comment by suchwerk** [comment]
Thanks Michael, i missed the `<dialog-outlet></dialog-outlet>`. Maybe a short hint in the example would be helpful.

**Comment by charitharumapperuma** [comment]
Actually I found out that app should import `MdlDialogModule` at the root level for date picker to work (importing it in a sub module won't work). I could not find that information in the given documentation. Even though that is straight forward to import it, I think that should be included in the documentation to be on the safe side.

**Comment by awmartin** [comment]
Neither of these actions (adding `<dialog-outlet></dialog-outlet>` or importing `MdlDialogModule` explicitly) has worked for me. Is there further guidance on making this work?

**Comment by charitharumapperuma** [comment]
`MdlDialogModule` must be imported as `MdlDialogModule.forRoot()` in `app.module.ts`
