### ISSUE TITLE
Option to add icon on button

### ISSUE THREAD

**Issue by howna13** [mseemann/angular2-mdl#863]
I think it would be an interesting feature to have buttons with text and icons.

**Comment by mseemann** [comment]
can you explain a little bit more what you are propose. maybe a code snippet how to use this feature. thx.

**Comment by howna13** [comment]
Right now we can add buttons with text or with icons, but not both at a time. It would be nice to have all the possibilities. Something like:

```
<button mdl-button mdl-button-type="raised" mdl-ripple>
   <mdl-icon>add</mdl-icon>
   <label>Share</label>
</button>
```

That would result in something like this:

![image](https://cloud.githubusercontent.com/assets/5635059/26159822/e848f874-3b1f-11e7-9488-1982f2de38de.png)

**Comment by mseemann** [comment]
if i write this:
```
<button mdl-button mdl-button-type="raised">
    <mdl-icon>account_box</mdl-icon>
    <label>Button</label>
</button>
```
i get this:
<img width="131" alt="bildschirmfoto 2017-05-20 um 17 10 15" src="https://cloud.githubusercontent.com/assets/555817/26276815/3bd44640-3d7f-11e7-8eef-b98dc30dcec9.png">


what am i missing :/
