### ISSUE TITLE
Breaks with final release of Angular2!

### ISSUE THREAD

**Issue by david-lehmann** [mseemann/angular2-mdl#87]
After upgrading to the final Version of Angular2 and using Angular-CLI.beta14 I'm getting the following Error:

> Unexpected value 'MdlModule' imported by the module 'AppModule'

Please fix this or provide a workaround as soon as possible, please.

**Comment by mseemann** [comment]
just checked this with my test project. can not see any problems using angular2-mdl@1.6 with angular 2.0 final.
