### ISSUE TITLE
Layout title not redrawing

### ISSUE THREAD

**Issue by grizzm0** [mseemann/angular2-mdl#89]
I'm not sure if this error is related to angular2-mdl or material-design-lite itself. But the pen at https://codepen.io/anon/pen/XjKdbp/ is not affected (mdl 1.2.1).

I updated to 1.7 yesterday and now I've started noticing that the layout title does not update properly after resizing the window.

[This is what happens](https://www.dropbox.com/s/axobs05j2n2btqk/Screenshot%202016-09-16%2011.31.55.png?dl=0) after resizing the window down to the mobile breakpoint. The drawer button moves into its proper location but the title bar does not become 100% wide. Simply clicking the title seems to trigger a change and the title becomes 100%.

The same issue appears when resizing from mobile to desktop but in this case the title gets hidden behind the drawer.

This is with **mdl-layout-fixed-header** and **mdl-layout-fixed-drawer** attributes

**Comment by grizzm0** [comment]
Here's a video demonstrating the issue aswell: https://youtu.be/S-x8nh-sDrI

**Comment by mseemann** [comment]
I'll check this asap...

**Comment by mseemann** [comment]
npm version 1.7.1. sorry i was too optimistic about zones and media query listeners...
