### ISSUE TITLE
Checkbox does not show checkmark in Angular 4 production

### ISSUE THREAD

**Issue by objecteer** [mseemann/angular2-mdl#891]
I use the mdl-checkbox in my Angular 4 application, and it works normally under "ng serve" and "ng build". However, when I tried to build the production code with "ng build --prod", checkmark is disappeared in all mdl-checkboxes.

**Comment by mseemann** [comment]
can't reproduce your problem. see **https://github.com/mseemann/angular-mdl-a4-angular-cli**
