### ISSUE TITLE
add semver carret to the 2.0.0 angular deps

### ISSUE THREAD

**Issue by mseemann** [mseemann/angular2-mdl#90]
... make sure this package will run with all versions < 3.0.0

**Comment by grizzm0** [comment]
I would rather use ~2.0.0 instead of ^2.0.0 as 2.1.0 is allowed minor breaks.

**Comment by mseemann** [comment]
they promised they will not :) 

http://angularjs.blogspot.de/:
the MAJOR version gets incremented when incompatible API changes are made to stable APIs,
the MINOR version gets incremented when backwards-compatible functionality are added,
the PATCH version gets incremented when backwards-compatible bug are fixed.
