### ISSUE TITLE
SelectAll functionality for TextField component

### ISSUE THREAD

**Issue by TycoT** [mseemann/angular2-mdl#932]
Is it possible to add a simple interface to Textfield to select all the text in the input field. 

Traditional way: inputElement.select();

Many thanks.

**Comment by mseemann** [comment]
because aot requires everything to be public :(  you can do the follwing:

```
<mdl-textfield
        #theFirstTextfield
        type="text">....
```

in your component:

`@ViewChild('theFirstTextfield') tf: MdlTextFieldComponent;`

and then you can call:
`this.tf.inputEl.nativeElement.select();`

**Comment by TycoT** [comment]
Hey, its working well, thank you so much for taking the time 👍
