### ISSUE TITLE
[mdl-dialog] Support click outside to close on specific condition

### ISSUE THREAD

**Issue by thaihacong** [mseemann/angular2-mdl#939]
Hi @mseemann, I am using mdlDialogService.showCustomDialog() with `clickOutsideToClose: true` options.
Sometimes, I need to **check for some conditions** to decide if the custom dialog could be closed or not.
My current solution is set `clickOutsideToClose: false`, and add another extra close button, which triggers `mdlDialogReference.hide()`.

Do you have any suggestion, so that I can listen to `click outside of the mdl-dialog events`, and check conditions before closing the dialog?
My idea is to expose a new method `onClickOutside()` in MdlDialogReference class.

**Comment by mseemann** [comment]
hi. i don't think that it is a good idea to change such a behavior. how should your users know that they can close a dialog with a click outside or not?

you can listen to backdrop click events:

```
  constructor(mdlDialogOutletService: MdlDialogOutletService) {

    this.mdlDialogOutletService.backdropClickEmitter.subscribe( () => {

    });
  }
```

but you can not prevent from closing the dialog. what you can do is listen to this event and close your dialog from your code.
