### ISSUE TITLE
mdl-dialogs are not closed when route changes

### ISSUE THREAD

**Issue by thaihacong** [mseemann/angular2-mdl#940]
In my application, I place `<dialog-outlet>` in `index.html` file as follow.
```
<body>
  <app-root>....</app-root>
  <dialog-outlet></dialog-outlet>
</body>
```

When I have mdl-dialog(s) opened, if I **navigate to other route by modifying URL**, then the new angular module inside `<app-root>` is loaded, but **all mdl-dialogs remain on the scree**n.
I think, mdl-dialogs should be all closed when I change the application route.

The same thing happens when I move `<dialog-outlet>` into `app.component.html` of app-module.

If this is the expected behavior of the mdl-dialog, how should I prevent user from navigating away while mdl-dialogs are still opened?

**Comment by mseemann** [comment]
it is intended - because the lib has no idea what is suitable for your app. you can use https://angular.io/docs/ts/latest/api/router/index/CanDeactivate-interface.html on the component that opens the dialog and prevent from route change or close the dialog.

**Comment by ericel** [comment]
I use `onDestroy` on dialog components to `closeAll` dialogs on route change.

```close(): void {
    this.dialog.closeAll();
  }

  ngOnDestroy (){
    this.close();
  }```
