### ISSUE TITLE
[mdl-tabs] Support more than one word in a tab.

### ISSUE THREAD

**Issue by rarenal** [mseemann/angular2-mdl#954]
Hello @mseemann ! I'm building an app using **angular2-mdl** and I found an issue using the component `mdl-tabs`. In some of my tabs I need to put more than one word, for example 'NEW FEATURES', but it seems to break the word on whitespace, so it will only show 'NEW' in the tab,

To solution this i have to put a different character than whitespace ('_' for example) an do some magic with CSS. 

I would support more than one word in tab because it can be a quite common use case for some applications.

**Comment by mseemann** [comment]
this is a "feature" of mdl. if you need something like this you need to change the css for .mdl-tabs__tab and add white-space: nowrap;

**Comment by rarenal** [comment]
Worked fine. Thank you @mseemann!!
