### ISSUE TITLE
Required invalid/touched form

### ISSUE THREAD

**Issue by Aorewen** [mseemann/angular2-mdl#96]
Hi, 

First of all, thanks for ur work.

Could u provide me a Plnkr with a form, inside a mdl textfield with required and minlenght attributes, with errors msgs ?

I tried this : 

```
  <div>
    <mdl-textfield label="Username" type="text" id="username" formControlName="username" floating-label pattern="^[a-zA-Z][a-zA-Z0-9-_\.]*" minlength="3"  ng-required="true"></mdl-textfield>
    <span class="mdl-tooltip mdl-tooltip--validation" for="username" ng-show="authForm.username.$invalid && authForm.username.$touched">
      <span ng-show="authForm.username.$error.required">Required.</span>
      <span ng-show="authForm.username.$error.pattern">Invalid pattern.</span>
      <span ng-show="authForm.username.$error.minlength">Minimum of three characters.</span>
    </span>
  </div>
```

but i can't see my errors msgs.

Thanks in advance,

**Comment by mseemann** [comment]
hi,
the attributes minlength="3"  ng-required="true are not supported. because of formControlName i suppose you are using reactive forms. pleas look at the source of the reactive forms example from the demos (https://github.com/mseemann/angular2-mdl/blob/master/src/app/reactiveforms/reactiveform.component.ts) on how to use validation.

**Comment by Aorewen** [comment]
ok, got it like ur demo.

Just simply, is it possible to have multiples validators and associated [error-msg] with ur MDL ReactiveForms ?

**Comment by mseemann** [comment]
multiple validators is no problem. just provide an array of validators. if you need different error messages i would suggest create the messages dynamically in your component and assign the message to the error-msg attribute ( [error-msg]="errorMessage"  )

```
public get errorMessage() {
    return what ever message you want....
}
```

**Comment by Aorewen** [comment]
thanks, i'll try this )

**Comment by tcd** [comment]
> hi,
> the attributes minlength="3" ng-required="true are not supported. because of formControlName i suppose you are using reactive forms. pleas look at the source of the reactive forms example from the demos (https://github.com/mseemann/angular2-mdl/blob/master/src/app/reactiveforms/reactiveform.component.ts) on how to use validation.

If anyone needs this, that file is now at https://github.com/mseemann/angular2-mdl/blob/master/projects/demo/src/app/reactiveforms/reactiveform.component.ts
