### ISSUE TITLE
material-components-web

### ISSUE THREAD

**Issue by petttro** [mseemann/angular2-mdl#972]
Hi Michael

Did you see new official google material-design css framework "material-components"?  
[GitHub](https://github.com/material-components/material-components-web) 
[Official site](https://material.io/components/web/catalog/)

They wrote that "Material Components for the web (MDC-Web) is the successor to the Material Design Lite (MDL) project." 
[Migrating from MDL](https://material.io/components/web/docs/migrating-from-mdl/)

What do you think about that and do you have a plans to migrate angular2-mdl framework from MDL to MDC?
It will be great to have ability to use it with Angular (2,4). 

P.S. Thank you very much for your amazing work!

**Comment by mseemann** [comment]
Hi. please have a look at: https://stackoverflow.com/questions/41949361/upgrading-to-material-design-lite-2-0. But I think it would be a complete rewritten component lib with no migrtaion possibilities from angular-mdl to a mdc version - at least with a lot of breaking chances.
