### ISSUE TITLE
MdlScreenSizeService is destroyed on MdlLayoutComponent destroy

### ISSUE THREAD

**Issue by mscu** [mseemann/angular2-mdl#973]
Hello Michael,

unfortunately i came accross another issue:

In the MdlLayoutComponent's onDestroy() the MdlScreensizeService is [destroyed](https://github.com/mseemann/angular2-mdl/blob/master/src/lib/components/layout/mdl-layout.component.ts#L305) and because it is a singleton the layout breaks if you go back from a different page not using mdllayout:

![mdl](https://cloud.githubusercontent.com/assets/545229/26447026/e90141ea-4146-11e7-925a-38501ccca11d.gif)

This is also valid if you have multiple instances of MdlLayout on different pages. As soon as you leave the first instance the service is destroyed and the second instance doesn't work properly anymore.
The only workaround is to provide the MdlScreenSizeService in the components using MdlLayout which leads to multiple instances which costs some performance.

In addition, the MdlScreenSIzeService is not usable as API as its state depends on the Layouts Lifecycle.

You have two options:

- Provide the service in mdllayout component so that a new instance is created every time. The downside is that the service cannot be used as API
- Remove the destruction of the service and provide it as singleton. The downside is that it might unnessesarily listen to the media query if users dont use mdllayout at all

I have created a sample project to demonstrate the issue:

https://github.com/mscu/mdl-layout

Thanks a lot and best regards
Matthias

**Comment by mseemann** [comment]
hi. thx for finding this. i think the second option is the right one.

**Comment by mscu** [comment]
Thnaks a lot for the quick fix :)
