### ISSUE TITLE
An opened dialog stays on screen if user presses 'back' to previous page.

### ISSUE THREAD

**Issue by TycoT** [mseemann/angular2-mdl#978]
Hi there, 
If dialog is open and user presses 'back button' (desktop or mobile), the dialog stays on screen. A user may expect the dialog to close or go away if they navigate away from the current page. You can test this on the demo page (http://mseemann.io/angular2-mdl/), navigate to the dialog page, try opening one of the dialogs, and press the back button on the browser.

My current solution feels...dirty, perhaps you have a better solution to this?

```
// in app.component.html, put the <dialog-outlet> here instead of index.html
<dialog-outlet></dialog-outlet>

// in app.component.ts
import { PlatformLocation } from '@angular/common'
...
constructor(private location: PlatformLocation, private elementRef: ElementRef) {
  // on 'back' 
  this.location.onPopState(() => {
        var el: HTMLElement = this.elementRef.nativeElement;

        var dialog = el.querySelector('.mdl-dialog');
        var backdrop = el.querySelector('.dialog-backdrop');

        el.removeChild(dialog);
        el.removeChild(backdrop);
      })
}
```

**Comment by mseemann** [comment]
please see https://github.com/mseemann/angular2-mdl/issues/940. the answer would be the same. also you find a way what to do to close the dialog if you think it's appropriate for your application.
