### ISSUE TITLE
Missing min/max on textfield

### ISSUE THREAD

**Issue by grizzm0** [mseemann/angular2-mdl#99]
Min/max attributes are missing in textfield with type number. 

See https://jsfiddle.net/hv28yrfv/1/

**Comment by mseemann** [comment]
this isn't difficult to add. Did i mention, that this project is open for pull requests? :)

**Comment by grizzm0** [comment]
Sure. :)

Not quite sure how it should work tho... 

Max/min is only allowed if type is number. Should I create another *ngIf just for this purpose?
What should default of min be if not set?
What should default of max be if not set?

**Comment by mseemann** [comment]
i would suggest do not any special logic. just propagate the attribute from the wrapper element down to the input element and let the browser implementation do the rest (like it was implemented for name or placeholder).

**Comment by simonschllng** [comment]
I can't test it atm, but hope this helps:
[min_max.patch.txt](https://github.com/mseemann/angular2-mdl/files/488018/min_max.patch.txt)

**Comment by grizzm0** [comment]
@simonschllng Feel free to create a PR if you already have a patch. I've been quite busy lately and haven't had the time to do so.

**Comment by mseemann** [comment]
@simonschllng Thanks for your help!
