### ISSUE TITLE
Issue with dialog in lazy loaded components

### ISSUE THREAD

**Issue by JSMike** [mseemann/angular2-mdl#997]
Hello 😄 ,

MdlDialogModule [imports the MdlDialogOutletModule with forRoot](https://github.com/mseemann/angular2-mdl/blob/master/src/lib/components/dialog/index.ts#L34). This causes issues when a lazy loaded component contains dialogs, when using a `<dialog-outlet>` on a parent that isn't lazy loaded, the outlet cannot be found. I would suggest adding the MdlDialogOutletService directly to the to the MdlDialogModule's forRoot function instead of calling forRoot on the MdlDialogOutletModule import. Unless there's a better pattern to follow.

Note: The error is currently resolved by importing MdlDialogModule with .forRoot() on both the main app module and the lazily loaded module, but this feels like an anti-pattern.

**Comment by mseemann** [comment]
hi. need to think about it...

**Comment by unixxxx** [comment]
any news about this issue?
